# Importing important libraries

In [1]:
import requests
from bs4 import BeautifulSoup
import re

In [2]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.common.exceptions import StaleElementReferenceException , NoSuchElementException , ElementClickInterceptedException

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import time

.

.

# Nike_Shoe_Men

# Navigating

In [3]:
driver = webdriver.Chrome()
driver.get("https://www.nike.com/")

In [4]:
search = driver.find_element(By.XPATH,"/html/body/div[3]/div/div[3]/header/div[1]/div[2]/div/div/div[1]/div/div/input")
search.send_keys('shoes')

In [5]:
search_button = driver.find_element(By.XPATH,"/html/body/div[3]/div/div[3]/header/div[1]/div[2]/div/div/div[1]/div/div/button[2]")
search_button.click()

In [6]:
men = driver.find_element(By.XPATH,"/html/body/div[4]/div/div/div[2]/div[4]/div/div[5]/div[1]/div[1]/div[2]/div/div/div/div/nav/div/div/div[1]/div/div/div/a[1]/div")
men.click()

.

.

.

# Web scrapping

In [7]:
i = 0
while(i<150):
    driver.execute_script("window.scrollBy(0,200)")
    i+=1
    time.sleep(3)
    
    
Nike_Shoe_price = []    
try:
    price= driver.find_elements(By.XPATH,'//div[@class="product-card__animation_wrapper"]')[:200]
    for pr in price:
        Nike_Shoe_price.append(pr.text)
except NoSuchElementException:
     Nike_Shoe_price.append('_')
        
    
Nike_Shoe_Name = []
try:
    Name= driver.find_elements(By.XPATH,'//div[@class="product-card__title"]')[:200]
    for na in Name:
        Nike_Shoe_Name.append(na.text)
except NoSuchElementException:
    Nike_Shoe_Name.append('_')
    
    
Nike_Shoe_Number_of_colour = []
try:
    Number_of_colour= driver.find_elements(By.XPATH,'//div[@class="product-card__count-item"]')[:200]
    for co in Number_of_colour:
        Nike_Shoe_Number_of_colour.append(co.text)
except NoSuchElementException:
    Nike_Shoe_Number_of_colour.append('_')
    

opening_url = []    
url = driver.find_elements(By.XPATH,'//a[@class="product-card__link-overlay"]')[:200]
for i in url:
    opening_url.append(i.get_attribute('href'))

In [8]:
print(len(Nike_Shoe_price),
len(Nike_Shoe_Name),
len(Nike_Shoe_Number_of_colour),
len(opening_url))

200 200 200 200

.

In [10]:
Nike_Shoe_Size1=[]
Nike_Shoe_Size2=[]
Nike_Shoe_Size3=[]
Nike_Shoe_Size4=[]
Nike_Shoe_Size5=[]
Nike_Shoe_Size6=[]
Nike_Shoe_Size7=[]
Nike_Shoe_Size8=[]
Nike_Shoe_Size9=[]
Nike_Shoe_Size10=[]
Nike_Shoe_Size11=[]
Nike_Shoe_Size12=[]
Nike_Shoe_Size13=[]
Nike_Shoe_Size14=[]
Nike_Shoe_Size15=[]
Nike_Shoe_Size16=[]
Nike_Shoe_Size17=[]
Nike_Shoe_Size18=[]
Nike_Shoe_Size19=[]
Nike_Shoe_Size20=[]
Nike_Shoe_Size21=[]
Nike_Shoe_Size22=[]
Nike_Shoe_Size23=[]
Nike_Shoe_Size24=[]
Nike_Shoe_Size25=[]

Nike_Shoe_colour = []
Nike_Shoe_Size_Count = []
Nike_Shoe_Product_Code = []
Nike_Shoe_Reviews = []
Nike_Shoe_Star_Rating = []

In [11]:
for p in opening_url:
    driver.get(p)
    time.sleep(5)
       
    try:
        size1= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[1]')
        Nike_Shoe_Size1.append(size1.text)
    except NoSuchElementException:
        Nike_Shoe_Size1.append('_')

    try:
        size2= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[2]')
        Nike_Shoe_Size2.append(size2.text)
    except NoSuchElementException:
        Nike_Shoe_Size2.append('_')
        
    try:
        size3= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[3]')
        Nike_Shoe_Size3.append(size3.text)
    except NoSuchElementException:
        Nike_Shoe_Size3.append('_')
        
    try:
        size4= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[4]')
        Nike_Shoe_Size4.append(size4.text)
    except NoSuchElementException:
        Nike_Shoe_Size4.append('_')
        
    try:
        size5= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[5]')
        Nike_Shoe_Size5.append(size5.text)
    except NoSuchElementException:
        Nike_Shoe_Size5.append('_')
        
    try:
        size6= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[6]')
        Nike_Shoe_Size6.append(size6.text)
    except NoSuchElementException:
        Nike_Shoe_Size6.append('_')
        
    try:
        size7= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[7]')
        Nike_Shoe_Size7.append(size7.text)
    except NoSuchElementException:
        Nike_Shoe_Size7.append('_')
        
    try:
        size8= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[8]')
        Nike_Shoe_Size8.append(size8.text)
    except NoSuchElementException:
        Nike_Shoe_Size8.append('_')
        
    try:
        size9= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[9]')
        Nike_Shoe_Size9.append(size9.text)
    except NoSuchElementException:
        Nike_Shoe_Size9.append('_')
        
    try:
        size10= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[10]')
        Nike_Shoe_Size10.append(size10.text)
    except NoSuchElementException:
        Nike_Shoe_Size10.append('_')
        
    try:
        size11= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[11]')
        Nike_Shoe_Size11.append(size11.text)
    except NoSuchElementException:
        Nike_Shoe_Size11.append('_')
        
    try:
        size12= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[12]')
        Nike_Shoe_Size12.append(size12.text)
    except NoSuchElementException:
        Nike_Shoe_Size12.append('_')
        
    try:
        size13= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[13]')
        Nike_Shoe_Size13.append(size13.text)
    except NoSuchElementException:
        Nike_Shoe_Size13.append('_')
        
    try:
        size14= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[14]')
        Nike_Shoe_Size14.append(size14.text)
    except NoSuchElementException:
        Nike_Shoe_Size14.append('_')
        
    try:
        size15= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[15]')
        Nike_Shoe_Size15.append(size15.text)
    except NoSuchElementException:
        Nike_Shoe_Size15.append('_')
        
    try:
        size16= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[16]')
        Nike_Shoe_Size16.append(size16.text)
    except NoSuchElementException:
        Nike_Shoe_Size16.append('_')
        
    try:
        size17= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[17]')
        Nike_Shoe_Size17.append(size17.text)
    except NoSuchElementException:
        Nike_Shoe_Size17.append('_')
        
    try:
        size18= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[18]')
        Nike_Shoe_Size18.append(size18.text)
    except NoSuchElementException:
        Nike_Shoe_Size18.append('_')
        
    try:
        size19= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[19]')
        Nike_Shoe_Size19.append(size19.text)
    except NoSuchElementException:
        Nike_Shoe_Size19.append('_')
        
    try:
        size20= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[20]')
        Nike_Shoe_Size20.append(size20.text)
    except NoSuchElementException:
        Nike_Shoe_Size20.append('_')
        
    try:
        size21= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[21]')
        Nike_Shoe_Size21.append(size21.text)
    except NoSuchElementException:
        Nike_Shoe_Size21.append('_')
        
    try:
        size22= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[22]')
        Nike_Shoe_Size22.append(size22.text)
    except NoSuchElementException:
        Nike_Shoe_Size22.append('_')
        
    try:
        size23= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[23]')
        Nike_Shoe_Size23.append(size23.text)
    except NoSuchElementException:
        Nike_Shoe_Size23.append('_')
        
    try:
        size24= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[24]')
        Nike_Shoe_Size24.append(size24.text)
    except NoSuchElementException:
        Nike_Shoe_Size24.append('_')
        
    try:
        size25= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[25]')
        Nike_Shoe_Size25.append(size25.text)
    except NoSuchElementException:
        Nike_Shoe_Size25.append('_')
        
        
    try:
        colour= driver.find_element(By.XPATH,'//li[@class="description-preview__color-description ncss-li"]')
        Nike_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        Nike_Shoe_colour.append('_')
        
    try:
        Size= driver.find_element(By.XPATH,'//label[@class="css-xf3ahq"]')
        Nike_Shoe_Size_Count.append(Size.text)
    except NoSuchElementException:
        Nike_Shoe_Size_Count.append('_')
    
    try:
        Product_Code= driver.find_element(By.XPATH,'//li[@class="description-preview__style-color ncss-li"]')
        Nike_Shoe_Product_Code.append(Product_Code.text)
    except NoSuchElementException:
        Nike_Shoe_Product_Code.append('_')
            
    try:
        drop = driver.find_element(By.XPATH,'//div[@class="css-n209rx"]')
        drop.click()
        Reviews= driver.find_element(By.XPATH,'//li[@class="review mb10-sm"]')
        Nike_Shoe_Reviews.append(Reviews.text)
    except NoSuchElementException:
        Nike_Shoe_Reviews.append('_')

    try:
        Rating= driver.find_element(By.XPATH,'//p[@class="d-sm-ib pl4-sm"]')
        Nike_Shoe_Star_Rating.append(Rating.text)
    except NoSuchElementException:
        Nike_Shoe_Star_Rating.append('_')

In [12]:
Nike_Shoe_Men = pd.DataFrame({
'Nike_Shoe_Name':Nike_Shoe_Name[:180],'Nike_Shoe_colour':Nike_Shoe_colour[:180],
'Nike_Shoe_Number_of_colour':Nike_Shoe_Number_of_colour[:180],'Nike_Shoe_price':Nike_Shoe_price[:180],
'Nike_Shoe_Product_Code':Nike_Shoe_Product_Code[:180],
'Nike_Shoe_Reviews':Nike_Shoe_Reviews[:180],
'Nike_Shoe_Star_Rating':Nike_Shoe_Star_Rating[:180],
'Nike_Shoe_Size1':Nike_Shoe_Size1[:180],
'Nike_Shoe_Size2':Nike_Shoe_Size2[:180],
'Nike_Shoe_Size3':Nike_Shoe_Size3[:180],
'Nike_Shoe_Size4':Nike_Shoe_Size4[:180],
'Nike_Shoe_Size5':Nike_Shoe_Size5[:180],
'Nike_Shoe_Size6':Nike_Shoe_Size6[:180],
'Nike_Shoe_Size7':Nike_Shoe_Size7[:180],
'Nike_Shoe_Size8':Nike_Shoe_Size8[:180],
'Nike_Shoe_Size9':Nike_Shoe_Size9[:180],
'Nike_Shoe_Size10':Nike_Shoe_Size10[:180],
'Nike_Shoe_Size11':Nike_Shoe_Size11[:180],
'Nike_Shoe_Size12':Nike_Shoe_Size12[:180],
'Nike_Shoe_Size13':Nike_Shoe_Size13[:180],
'Nike_Shoe_Size14':Nike_Shoe_Size14[:180],
'Nike_Shoe_Size15':Nike_Shoe_Size15[:180],
'Nike_Shoe_Size16':Nike_Shoe_Size16[:180],
'Nike_Shoe_Size17':Nike_Shoe_Size17[:180],
'Nike_Shoe_Size18':Nike_Shoe_Size18[:180],
'Nike_Shoe_Size19':Nike_Shoe_Size19[:180],
'Nike_Shoe_Size20':Nike_Shoe_Size20[:180],
'Nike_Shoe_Size21':Nike_Shoe_Size21[:180],
'Nike_Shoe_Size22':Nike_Shoe_Size22[:180],
'Nike_Shoe_Size23':Nike_Shoe_Size23[:180],
'Nike_Shoe_Size24':Nike_Shoe_Size24[:180],
'Nike_Shoe_Size25':Nike_Shoe_Size25[:180],
'opening_url':opening_url[:180]})

In [15]:
Nike_Shoe_Men.to_csv('Nike_Shoe_Man.csv')

In [4]:
Nike_Shoe_Man=pd.read_csv('Nike_Shoe_Man.csv')

In [5]:
Nike_Shoe_Man['gender'] = 'men'
Nike_Shoe_Man['brand'] = 'Nike'

In [6]:
Nike_Shoe_Man

,Unnamed: 0,Nike_Shoe_Name,Nike_Shoe_colour,Nike_Shoe_Number_of_colour,Nike_Shoe_price,Nike_Shoe_Product_Code,Nike_Shoe_Reviews,Nike_Shoe_Star_Rating,Nike_Shoe_Size1,Nike_Shoe_Size2,...,Nike_Shoe_Size19,Nike_Shoe_Size20,Nike_Shoe_Size21,Nike_Shoe_Size22,Nike_Shoe_Size23,Nike_Shoe_Size24,Nike_Shoe_Size25,opening_url,gender,brand
0,0,Nike Air Force 1 '07,Colour Shown: White/White,2 Colours,MRP : ₹ 7 495.00,Style: CW2288-111,Best I ever had lol n a sneaker\nIshmael367917...,4.8 Stars,UK 5.5,UK 6 (EU 39),...,UK 16,UK 17,_,_,_,_,_,https://www.nike.com/in/t/air-force-1-07-shoes...,men,Nike
1,1,Nike Court Vision Low,Colour Shown: Sail/Light Orewood Brown/White/B...,1 Colour,MRP : ₹ 5 695.00,Style: FQ8075-133,_,0 Stars,UK 5.5,UK 6 (EU 39),...,_,_,_,_,_,_,_,https://www.nike.com/in/t/court-vision-low-sho...,men,Nike
2,2,Nike Dunk Low Retro Premium,Colour Shown: Deep Jungle/Light Silver/Deep Ju...,1 Colour,MRP : ₹ 9 695.00,Style: FB8896-300,Adrian933928090 - 10 Nov 2023\nMy Sister bough...,5 Stars,UK 6 (EU 40),UK 6.5,...,_,_,_,_,_,_,_,https://www.nike.com/in/t/dunk-low-retro-shoes...,men,Nike
3,3,Nike Air Max 90,Colour Shown: Anthracite/Black/Mystic Red/Summ...,1 Colour,MRP : ₹ 11 895.00,Style: FB9658-001,Airmax 90\nbrigidot440749820 - 28 Nov 2023\nGr...,4.8 Stars,UK 6 (EU 40),UK 6.5,...,_,_,_,_,_,_,_,https://www.nike.com/in/t/air-max-90-shoes-0MB...,men,Nike
4,4,Nike Air Force 1 '07 Pro Tech,Colour Shown: Light Silver/Clear/Light Silver,3 Colours,MRP : ₹ 13 995.00,Style: FB8875-002,Skank898735936 - 16 Nov 2023\nLoving ❤️ it ✔️ ...,4.6 Stars,UK 5.5,UK 6 (EU 39),...,_,_,_,_,_,_,_,https://www.nike.com/in/t/air-force-1-07-pro-t...,men,Nike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,Sabrina 1 By You,Colour Shown: Multi-Colour/Multi-Colour/Multi-...,1 Colour,MRP : ₹ 13 995.00,Style: FJ4036-900,_,_,_,_,...,_,_,_,_,_,_,_,https://www.nike.com/in/u/custom-sabrina-1-by-...,men,Nike
176,176,Nike Air Zoom Infinity Tour NEXT% Boa,Colour Shown: White/Photo Blue/Black,1 Colour,MRP : ₹ 17 495.00,Style: DJ5590-103,Awesome but an air leak\nTrevorL410082050 - 18...,4.5 Stars,UK 5.5,UK 6 (EU 39),...,_,_,_,_,_,_,_,https://www.nike.com/in/t/air-zoom-infinity-to...,men,Nike
177,177,Nike SB Zoom Blazer Low Pro GT,Colour Shown: White/White/White/Black,3 Colours,MRP : ₹ 6 795.00,Style: DC7695-100,Shred ready yet casually comfirtable\nKeithS12...,4.9 Stars,UK 5.5,UK 6 (EU 39),...,_,_,_,_,_,_,_,https://www.nike.com/in/t/sb-zoom-blazer-low-p...,men,Nike
178,178,LeBron Witness 8 EP,Colour Shown: White/Light Smoke Grey/Black,4 Colours,MRP : ₹ 8 695.00,Style: FB2237-100,_,0 Stars,UK 6 (EU 40),UK 6.5,...,_,_,_,_,_,_,_,https://www.nike.com/in/t/lebron-witness-8-ep-...,men,Nike
179,179,Nike ISPA Universal,Colour Shown: Earth/Earth,1 Colour,MRP : ₹ 9 695.00,Style: DM0886-200,These are a GO!\nCrossMose - 17 Nov 2023\nI re...,3 Stars,UK 6 (EU 40),UK 7,...,_,_,_,_,_,_,_,https://www.nike.com/in/t/ispa-universal-shoes...,men,Nike

.

.

In [7]:
Nike_Shoe_Man.to_csv('Nike_Shoe_Man.csv')

In [75]:
Nike_Shoe_Man=pd.read_csv('Nike_Shoe_Man.csv')

In [22]:
driver.close()

.

.

# Nike_Shoe_women

In [26]:
driver = webdriver.Chrome()
driver.get("https://www.nike.com/")

In [11]:
search = driver.find_element(By.XPATH,"/html/body/div[3]/div/div[3]/header/div[1]/div[2]/div/div/div[1]/div/div/input")
search.send_keys('shoes')
search_button = driver.find_element(By.XPATH,"/html/body/div[3]/div/div[3]/header/div[1]/div[2]/div/div/div[1]/div/div/button[2]")
search_button.click()

In [12]:
women = driver.find_element(By.XPATH,"/html/body/div[4]/div/div/div[2]/div[4]/div/div[5]/div[1]/div[1]/div[2]/div/div/div/div/nav/div/div/div[1]/div/div/div/a[2]/div")
women.click()

In [18]:
i = 0
while(i<150):
    driver.execute_script("window.scrollBy(0,200)")
    i+=1
    time.sleep(3)
    
    
Nike_Shoe_price = []    
try:
    price= driver.find_elements(By.XPATH,'//div[@class="product-card__animation_wrapper"]')[:200]
    for pr in price:
        Nike_Shoe_price.append(pr.text)
except NoSuchElementException:
     Nike_Shoe_price.append('_')
        
    
Nike_Shoe_Name = []
try:
    Name= driver.find_elements(By.XPATH,'//div[@class="product-card__title"]')[:200]
    for na in Name:
        Nike_Shoe_Name.append(na.text)
except NoSuchElementException:
    Nike_Shoe_Name.append('_')
    
    
Nike_Shoe_Number_of_colour = []
try:
    Number_of_colour= driver.find_elements(By.XPATH,'//div[@class="product-card__count-item"]')[:200]
    for co in Number_of_colour:
        Nike_Shoe_Number_of_colour.append(co.text)
except NoSuchElementException:
    Nike_Shoe_Number_of_colour.append('_')
    

opening_url = []    
url = driver.find_elements(By.XPATH,'//a[@class="product-card__link-overlay"]')[:200]
for i in url:
    opening_url.append(i.get_attribute('href'))

In [19]:
print(len(Nike_Shoe_price),
len(Nike_Shoe_Name),
len(Nike_Shoe_Number_of_colour),
len(opening_url))

200 200 200 200

In [ ]:
Nike_Shoe_Size1=[]
Nike_Shoe_Size2=[]
Nike_Shoe_Size3=[]
Nike_Shoe_Size4=[]
Nike_Shoe_Size5=[]
Nike_Shoe_Size6=[]
Nike_Shoe_Size7=[]
Nike_Shoe_Size8=[]
Nike_Shoe_Size9=[]
Nike_Shoe_Size10=[]
Nike_Shoe_Size11=[]
Nike_Shoe_Size12=[]
Nike_Shoe_Size13=[]
Nike_Shoe_Size14=[]
Nike_Shoe_Size15=[]
Nike_Shoe_Size16=[]
Nike_Shoe_Size17=[]
Nike_Shoe_Size18=[]
Nike_Shoe_Size19=[]
Nike_Shoe_Size20=[]
Nike_Shoe_Size21=[]
Nike_Shoe_Size22=[]
Nike_Shoe_Size23=[]
Nike_Shoe_Size24=[]
Nike_Shoe_Size25=[]

Nike_Shoe_colour = []
Nike_Shoe_Size_Count = []
Nike_Shoe_Product_Code = []
Nike_Shoe_Reviews = []
Nike_Shoe_Star_Rating = []

for p in opening_url:
    driver.get(p)
    time.sleep(15)
       
    try:
        size1= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[1]')
        Nike_Shoe_Size1.append(size1.text)
    except NoSuchElementException:
        Nike_Shoe_Size1.append('_')

    try:
        size2= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[2]')
        Nike_Shoe_Size2.append(size2.text)
    except NoSuchElementException:
        Nike_Shoe_Size2.append('_')
        
    try:
        size3= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[3]')
        Nike_Shoe_Size3.append(size3.text)
    except NoSuchElementException:
        Nike_Shoe_Size3.append('_')
        
    try:
        size4= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[4]')
        Nike_Shoe_Size4.append(size4.text)
    except NoSuchElementException:
        Nike_Shoe_Size4.append('_')
        
    try:
        size5= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[5]')
        Nike_Shoe_Size5.append(size5.text)
    except NoSuchElementException:
        Nike_Shoe_Size5.append('_')
        
    try:
        size6= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[6]')
        Nike_Shoe_Size6.append(size6.text)
    except NoSuchElementException:
        Nike_Shoe_Size6.append('_')
        
    try:
        size7= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[7]')
        Nike_Shoe_Size7.append(size7.text)
    except NoSuchElementException:
        Nike_Shoe_Size7.append('_')
        
    try:
        size8= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[8]')
        Nike_Shoe_Size8.append(size8.text)
    except NoSuchElementException:
        Nike_Shoe_Size8.append('_')
        
    try:
        size9= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[9]')
        Nike_Shoe_Size9.append(size9.text)
    except NoSuchElementException:
        Nike_Shoe_Size9.append('_')
        
    try:
        size10= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[10]')
        Nike_Shoe_Size10.append(size10.text)
    except NoSuchElementException:
        Nike_Shoe_Size10.append('_')
        
    try:
        size11= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[11]')
        Nike_Shoe_Size11.append(size11.text)
    except NoSuchElementException:
        Nike_Shoe_Size11.append('_')
        
    try:
        size12= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[12]')
        Nike_Shoe_Size12.append(size12.text)
    except NoSuchElementException:
        Nike_Shoe_Size12.append('_')
        
    try:
        size13= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[13]')
        Nike_Shoe_Size13.append(size13.text)
    except NoSuchElementException:
        Nike_Shoe_Size13.append('_')
        
    try:
        size14= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[14]')
        Nike_Shoe_Size14.append(size14.text)
    except NoSuchElementException:
        Nike_Shoe_Size14.append('_')
        
    try:
        size15= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[15]')
        Nike_Shoe_Size15.append(size15.text)
    except NoSuchElementException:
        Nike_Shoe_Size15.append('_')
        
    try:
        size16= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[16]')
        Nike_Shoe_Size16.append(size16.text)
    except NoSuchElementException:
        Nike_Shoe_Size16.append('_')
        
    try:
        size17= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[17]')
        Nike_Shoe_Size17.append(size17.text)
    except NoSuchElementException:
        Nike_Shoe_Size17.append('_')
        
    try:
        size18= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[18]')
        Nike_Shoe_Size18.append(size18.text)
    except NoSuchElementException:
        Nike_Shoe_Size18.append('_')
        
    try:
        size19= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[19]')
        Nike_Shoe_Size19.append(size19.text)
    except NoSuchElementException:
        Nike_Shoe_Size19.append('_')
        
    try:
        size20= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[20]')
        Nike_Shoe_Size20.append(size20.text)
    except NoSuchElementException:
        Nike_Shoe_Size20.append('_')
        
    try:
        size21= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[21]')
        Nike_Shoe_Size21.append(size21.text)
    except NoSuchElementException:
        Nike_Shoe_Size21.append('_')
        
    try:
        size22= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[22]')
        Nike_Shoe_Size22.append(size22.text)
    except NoSuchElementException:
        Nike_Shoe_Size22.append('_')
        
    try:
        size23= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[23]')
        Nike_Shoe_Size23.append(size23.text)
    except NoSuchElementException:
        Nike_Shoe_Size23.append('_')
        
    try:
        size24= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[24]')
        Nike_Shoe_Size24.append(size24.text)
    except NoSuchElementException:
        Nike_Shoe_Size24.append('_')
        
    try:
        size25= driver.find_element(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]/div[25]')
        Nike_Shoe_Size25.append(size25.text)
    except NoSuchElementException:
        Nike_Shoe_Size25.append('_')
    

        
    try:
        colour= driver.find_element(By.XPATH,'//li[@class="description-preview__color-description ncss-li"]')
        Nike_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        Nike_Shoe_colour.append('_')
        
    try:
        Size= driver.find_element(By.XPATH,'//label[@class="css-xf3ahq"]')
        Nike_Shoe_Size_Count.append(Size.text)
    except NoSuchElementException:
        Nike_Shoe_Size_Count.append('_')
    
    try:
        Product_Code= driver.find_element(By.XPATH,'//li[@class="description-preview__style-color ncss-li"]')
        Nike_Shoe_Product_Code.append(Product_Code.text)
    except NoSuchElementException:
        Nike_Shoe_Product_Code.append('_')
            
    try:
        drop = driver.find_element(By.XPATH,'//div[@class="css-n209rx"]')
        drop.click()
        Reviews= driver.find_element(By.XPATH,'//p[@style="overflow-wrap: break-word;"]')
        Nike_Shoe_Reviews.append(Reviews.text)
    except NoSuchElementException:
        Nike_Shoe_Reviews.append('_')

    try:
        Rating= driver.find_element(By.XPATH,'//p[@class="d-sm-ib pl4-sm"]')
        Nike_Shoe_Star_Rating.append(Rating.text)
    except NoSuchElementException:
        Nike_Shoe_Star_Rating.append('_')

In [ ]:
Nike_Shoe_women = pd.DataFrame({
'Nike_Shoe_Name':Nike_Shoe_Name[:120],'Nike_Shoe_colour':Nike_Shoe_colour[:120],
'Nike_Shoe_Number_of_colour':Nike_Shoe_Number_of_colour[:120],'Nike_Shoe_price':Nike_Shoe_price[:120],
'Nike_Shoe_Product_Code':Nike_Shoe_Product_Code[:120],
'Nike_Shoe_Reviews':Nike_Shoe_Reviews[:120],
'Nike_Shoe_Star_Rating':Nike_Shoe_Star_Rating[:120],
'Nike_Shoe_Size1':Nike_Shoe_Size1[:120],
'Nike_Shoe_Size2':Nike_Shoe_Size2[:120],
'Nike_Shoe_Size3':Nike_Shoe_Size3[:120],
'Nike_Shoe_Size4':Nike_Shoe_Size4[:120],
'Nike_Shoe_Size5':Nike_Shoe_Size5[:120],
'Nike_Shoe_Size6':Nike_Shoe_Size6[:120],
'Nike_Shoe_Size7':Nike_Shoe_Size7[:120],
'Nike_Shoe_Size8':Nike_Shoe_Size8[:120],
'Nike_Shoe_Size9':Nike_Shoe_Size9[:120],
'Nike_Shoe_Size10':Nike_Shoe_Size10[:120],
'Nike_Shoe_Size11':Nike_Shoe_Size11[:120],
'Nike_Shoe_Size12':Nike_Shoe_Size12[:120],
'Nike_Shoe_Size13':Nike_Shoe_Size13[:120],
'Nike_Shoe_Size14':Nike_Shoe_Size14[:120],
'Nike_Shoe_Size15':Nike_Shoe_Size15[:120],
'Nike_Shoe_Size16':Nike_Shoe_Size16[:120],
'Nike_Shoe_Size17':Nike_Shoe_Size17[:120],
'Nike_Shoe_Size18':Nike_Shoe_Size18[:120],
'Nike_Shoe_Size19':Nike_Shoe_Size19[:120],
'Nike_Shoe_Size20':Nike_Shoe_Size20[:120],
'Nike_Shoe_Size21':Nike_Shoe_Size21[:120],
'Nike_Shoe_Size22':Nike_Shoe_Size22[:120],
'Nike_Shoe_Size23':Nike_Shoe_Size23[:120],
'Nike_Shoe_Size24':Nike_Shoe_Size24[:120],
'Nike_Shoe_Size25':Nike_Shoe_Size25[:120],
'opening_url':opening_url[:120]})

In [ ]:
Nike_Shoe_women.to_csv('Nike_Shoe_women.csv')

In [32]:
len(Nike_Shoe_Size2)

120

In [35]:
Nike_Shoe_women

,Unnamed: 0,Nike_Shoe_Name,Nike_Shoe_colour,Nike_Shoe_Number_of_colour,Nike_Shoe_price,Nike_Shoe_Size_Count,Nike_Shoe_Product_Code,Nike_Shoe_Reviews,Nike_Shoe_Star_Rating,opening_url,...,Nike_Shoe_Size16,Nike_Shoe_Size17,Nike_Shoe_Size18,Nike_Shoe_Size19,Nike_Shoe_Size20,Nike_Shoe_Size21,Nike_Shoe_Size22,Nike_Shoe_Size23,Nike_Shoe_Size24,Nike_Shoe_Size25
0,0,Nike Air Force 1 '07 EasyOn,Colour Shown: White/White/White,1 Colour,MRP : ₹ 9 695.00,UK 5.5,Style: FD1146-100,Awesome!! Fits really good very comfortable an...,4.6 Stars,https://www.nike.com/in/t/air-force-1-07-easyo...,...,UK 13,UK 14,_,_,_,_,_,_,_,_
1,1,Nike Air Force 1 '07 NN,Colour Shown: Summit White/Metallic Silver/Bro...,1 Colour,MRP : ₹ 9 695.00,UK 2.5,Style: DV3808-101,Brought my usual size 4.1/2 true to size and c...,4.9 Stars,https://www.nike.com/in/t/air-force-1-07-nn-sh...,...,_,_,_,_,_,_,_,_,_,_
2,2,Nike Dunk Low Twist,Colour Shown: Coconut Milk/White/Vivid Sulphur,5 Colours,MRP : ₹ 9 695.00,UK 2.5,Style: DZ2794-100,Fits great and looks good . Bought it about 2 ...,4.6 Stars,https://www.nike.com/in/t/dunk-low-twist-shoes...,...,_,_,_,_,_,_,_,_,_,_
3,3,Nike Air Force 1 Shadow,Colour Shown: Phantom/Pink Oxford/White/Red St...,1 Colour,MRP : ₹ 11 895.00,UK 2.5,Style: DZ1847-001,Love these trainers & love the colours and the...,5 Stars,https://www.nike.com/in/t/air-force-1-shadow-s...,...,_,_,_,_,_,_,_,_,_,_
4,4,Air Jordan 1 Low SE,Colour Shown: Sky J Orange/Sail,1 Colour,MRP : ₹ 10 295.00,UK 2.5,Style: FN3722-801,"The color is gorgeous, I usually wear a 6.5 an...",4.8 Stars,https://www.nike.com/in/t/air-jordan-1-low-se-...,...,_,_,_,_,_,_,_,_,_,_
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,115,Nike Blazer Low '77,Colour Shown: White/White/White/White,2 Colours,MRP : ₹ 7 195.00,UK 2.5,Style: DC4769-101,So cute. Fit TTS. Highly recommend!,4.3 Stars,https://www.nike.com/in/t/blazer-low-77-shoes-...,...,_,_,_,_,_,_,_,_,_,_
116,116,Nike Pegasus Trail 4 GORE-TEX By You,Colour Shown: Multi-Colour/Multi-Colour,6 Colours,MRP : ₹ 17 495.00,UK 2.5,Style: FJ8896-900,_,_,https://www.nike.com/in/u/custom-pegasus-trail...,...,_,_,_,_,_,_,_,_,_,_
117,117,Nike Gripknit Phantom GX Elite FG By You,_,4 Colours,MRP : ₹ 25 995.00,_,_,_,_,https://www.nike.com/in/u/custom-phantom-elite...,...,_,_,_,_,_,_,_,_,_,_
118,118,Nike Blazer Low '77 By You,Colour Shown: Multi-Colour/Multi-Colour,6 Colours,MRP : ₹ 10 295.00,UK 2.5,Style: DZ2653-900,_,_,https://www.nike.com/in/u/custom-nike-blazer-l...,...,_,_,_,_,_,_,_,_,_,_
119,119,Nike Pegasus 40 By You,_,14 Colours,MRP : ₹ 14 995.00,_,_,_,_,https://www.nike.com/in/u/custom-pegasus-40-by...,...,_,_,_,_,_,_,_,_,_,_

In [87]:
Nike_Shoe_women['gender'] = 'women'
Nike_Shoe_women['brand'] = 'Nike'

In [43]:
Nike_Shoe_women.to_csv('Nike_Shoe_women1.csv')

In [12]:
Nike_Shoe_women1=pd.read_csv('Nike_Shoe_women1.csv')

In [15]:
Nike_Shoe_women1 = Nike_Shoe_women1.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1)

In [16]:
Nike_Shoe_women1

,Nike_Shoe_Name,Nike_Shoe_colour,Nike_Shoe_Number_of_colour,Nike_Shoe_price,Nike_Shoe_Size_Count,Nike_Shoe_Product_Code,Nike_Shoe_Reviews,Nike_Shoe_Star_Rating,opening_url,Nike_Shoe_Size1,...,Nike_Shoe_Size18,Nike_Shoe_Size19,Nike_Shoe_Size20,Nike_Shoe_Size21,Nike_Shoe_Size22,Nike_Shoe_Size23,Nike_Shoe_Size24,Nike_Shoe_Size25,gender,brand
0,Nike Air Force 1 '07 EasyOn,Colour Shown: White/White/White,1 Colour,MRP : ₹ 9 695.00,UK 5.5,Style: FD1146-100,Awesome!! Fits really good very comfortable an...,4.6 Stars,https://www.nike.com/in/t/air-force-1-07-easyo...,UK 5.5,...,_,_,_,_,_,_,_,_,women,Nike
1,Nike Air Force 1 '07 NN,Colour Shown: Summit White/Metallic Silver/Bro...,1 Colour,MRP : ₹ 9 695.00,UK 2.5,Style: DV3808-101,Brought my usual size 4.1/2 true to size and c...,4.9 Stars,https://www.nike.com/in/t/air-force-1-07-nn-sh...,UK 2.5,...,_,_,_,_,_,_,_,_,women,Nike
2,Nike Dunk Low Twist,Colour Shown: Coconut Milk/White/Vivid Sulphur,5 Colours,MRP : ₹ 9 695.00,UK 2.5,Style: DZ2794-100,Fits great and looks good . Bought it about 2 ...,4.6 Stars,https://www.nike.com/in/t/dunk-low-twist-shoes...,UK 2.5,...,_,_,_,_,_,_,_,_,women,Nike
3,Nike Air Force 1 Shadow,Colour Shown: Phantom/Pink Oxford/White/Red St...,1 Colour,MRP : ₹ 11 895.00,UK 2.5,Style: DZ1847-001,Love these trainers & love the colours and the...,5 Stars,https://www.nike.com/in/t/air-force-1-shadow-s...,UK 2.5,...,_,_,_,_,_,_,_,_,women,Nike
4,Air Jordan 1 Low SE,Colour Shown: Sky J Orange/Sail,1 Colour,MRP : ₹ 10 295.00,UK 2.5,Style: FN3722-801,"The color is gorgeous, I usually wear a 6.5 an...",4.8 Stars,https://www.nike.com/in/t/air-jordan-1-low-se-...,UK 2.5,...,_,_,_,_,_,_,_,_,women,Nike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Nike Blazer Low '77,Colour Shown: White/White/White/White,2 Colours,MRP : ₹ 7 195.00,UK 2.5,Style: DC4769-101,So cute. Fit TTS. Highly recommend!,4.3 Stars,https://www.nike.com/in/t/blazer-low-77-shoes-...,UK 2.5,...,_,_,_,_,_,_,_,_,women,Nike
116,Nike Pegasus Trail 4 GORE-TEX By You,Colour Shown: Multi-Colour/Multi-Colour,6 Colours,MRP : ₹ 17 495.00,UK 2.5,Style: FJ8896-900,_,_,https://www.nike.com/in/u/custom-pegasus-trail...,_,...,_,_,_,_,_,_,_,_,women,Nike
117,Nike Gripknit Phantom GX Elite FG By You,_,4 Colours,MRP : ₹ 25 995.00,_,_,_,_,https://www.nike.com/in/u/custom-phantom-elite...,_,...,_,_,_,_,_,_,_,_,women,Nike
118,Nike Blazer Low '77 By You,Colour Shown: Multi-Colour/Multi-Colour,6 Colours,MRP : ₹ 10 295.00,UK 2.5,Style: DZ2653-900,_,_,https://www.nike.com/in/u/custom-nike-blazer-l...,_,...,_,_,_,_,_,_,_,_,women,Nike
119,Nike Pegasus 40 By You,_,14 Colours,MRP : ₹ 14 995.00,_,_,_,_,https://www.nike.com/in/u/custom-pegasus-40-by...,_,...,_,_,_,_,_,_,_,_,women,Nike

In [47]:
driver.close()

.

.

.

In [18]:
Nike_Shoe_Man = pd.read_csv('Nike_Shoe_Man.csv')

In [17]:
Nike_Shoe = pd.concat([Nike_Shoe_women1,Nike_Shoe_Man],ignore_index=True)
Nike_Shoe = Nike_Shoe.drop('Unnamed: 0',axis=1)

In [18]:
Nike_Shoe

,Nike_Shoe_Name,Nike_Shoe_colour,Nike_Shoe_Number_of_colour,Nike_Shoe_price,Nike_Shoe_Size_Count,Nike_Shoe_Product_Code,Nike_Shoe_Reviews,Nike_Shoe_Star_Rating,opening_url,Nike_Shoe_Size1,...,Nike_Shoe_Size18,Nike_Shoe_Size19,Nike_Shoe_Size20,Nike_Shoe_Size21,Nike_Shoe_Size22,Nike_Shoe_Size23,Nike_Shoe_Size24,Nike_Shoe_Size25,gender,brand
0,Nike Air Force 1 '07 EasyOn,Colour Shown: White/White/White,1 Colour,MRP : ₹ 9 695.00,UK 5.5,Style: FD1146-100,Awesome!! Fits really good very comfortable an...,4.6 Stars,https://www.nike.com/in/t/air-force-1-07-easyo...,UK 5.5,...,_,_,_,_,_,_,_,_,women,Nike
1,Nike Air Force 1 '07 NN,Colour Shown: Summit White/Metallic Silver/Bro...,1 Colour,MRP : ₹ 9 695.00,UK 2.5,Style: DV3808-101,Brought my usual size 4.1/2 true to size and c...,4.9 Stars,https://www.nike.com/in/t/air-force-1-07-nn-sh...,UK 2.5,...,_,_,_,_,_,_,_,_,women,Nike
2,Nike Dunk Low Twist,Colour Shown: Coconut Milk/White/Vivid Sulphur,5 Colours,MRP : ₹ 9 695.00,UK 2.5,Style: DZ2794-100,Fits great and looks good . Bought it about 2 ...,4.6 Stars,https://www.nike.com/in/t/dunk-low-twist-shoes...,UK 2.5,...,_,_,_,_,_,_,_,_,women,Nike
3,Nike Air Force 1 Shadow,Colour Shown: Phantom/Pink Oxford/White/Red St...,1 Colour,MRP : ₹ 11 895.00,UK 2.5,Style: DZ1847-001,Love these trainers & love the colours and the...,5 Stars,https://www.nike.com/in/t/air-force-1-shadow-s...,UK 2.5,...,_,_,_,_,_,_,_,_,women,Nike
4,Air Jordan 1 Low SE,Colour Shown: Sky J Orange/Sail,1 Colour,MRP : ₹ 10 295.00,UK 2.5,Style: FN3722-801,"The color is gorgeous, I usually wear a 6.5 an...",4.8 Stars,https://www.nike.com/in/t/air-jordan-1-low-se-...,UK 2.5,...,_,_,_,_,_,_,_,_,women,Nike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,Sabrina 1 By You,Colour Shown: Multi-Colour/Multi-Colour/Multi-...,1 Colour,MRP : ₹ 13 995.00,NaN,Style: FJ4036-900,_,_,https://www.nike.com/in/u/custom-sabrina-1-by-...,_,...,_,_,_,_,_,_,_,_,men,Nike
296,Nike Air Zoom Infinity Tour NEXT% Boa,Colour Shown: White/Photo Blue/Black,1 Colour,MRP : ₹ 17 495.00,NaN,Style: DJ5590-103,Awesome but an air leak\nTrevorL410082050 - 18...,4.5 Stars,https://www.nike.com/in/t/air-zoom-infinity-to...,UK 5.5,...,_,_,_,_,_,_,_,_,men,Nike
297,Nike SB Zoom Blazer Low Pro GT,Colour Shown: White/White/White/Black,3 Colours,MRP : ₹ 6 795.00,NaN,Style: DC7695-100,Shred ready yet casually comfirtable\nKeithS12...,4.9 Stars,https://www.nike.com/in/t/sb-zoom-blazer-low-p...,UK 5.5,...,_,_,_,_,_,_,_,_,men,Nike
298,LeBron Witness 8 EP,Colour Shown: White/Light Smoke Grey/Black,4 Colours,MRP : ₹ 8 695.00,NaN,Style: FB2237-100,_,0 Stars,https://www.nike.com/in/t/lebron-witness-8-ep-...,UK 6 (EU 40),...,_,_,_,_,_,_,_,_,men,Nike
299,Nike ISPA Universal,Colour Shown: Earth/Earth,1 Colour,MRP : ₹ 9 695.00,NaN,Style: DM0886-200,These are a GO!\nCrossMose - 17 Nov 2023\nI re...,3 Stars,https://www.nike.com/in/t/ispa-universal-shoes...,UK 6 (EU 40),...,_,_,_,_,_,_,_,_,men,Nike

In [19]:
a=Nike_Shoe['Nike_Shoe_Number_of_colour'].str.split(' ',expand=True)
a=a.drop(1,axis=1)
Nike_Shoe['Nike_Shoe_Number_of_colour'] = a

In [20]:
b=Nike_Shoe['Nike_Shoe_colour'].str.split(':',expand=True)
b=b.drop(0,axis=1)

In [21]:
Nike_Shoe['Nike_Shoe_colour']=b
Nike_Shoe[['colour1','colour2','colour3','colour4']] = Nike_Shoe['Nike_Shoe_colour'].str.split('/',expand=True)
Nike_Shoe=Nike_Shoe.drop('Nike_Shoe_colour',axis=1)

In [22]:
c=Nike_Shoe['Nike_Shoe_Star_Rating'].str.split(' ',expand=True)
c=c.drop(1,axis=1)
Nike_Shoe['Nike_Shoe_Star_Rating'] = c

In [23]:
d=Nike_Shoe['Nike_Shoe_price'].str.split(':',expand=True)
d=d.drop(0,axis=1)
d=d[1].str.split(' ',2,expand=True)
d=d.drop([0,1],axis=1)
d=d[2].str.replace(' ','')
Nike_Shoe['Nike_Shoe_price']=d

In [24]:
Nike_Shoe

,Nike_Shoe_Name,Nike_Shoe_Number_of_colour,Nike_Shoe_price,Nike_Shoe_Size_Count,Nike_Shoe_Product_Code,Nike_Shoe_Reviews,Nike_Shoe_Star_Rating,opening_url,Nike_Shoe_Size1,Nike_Shoe_Size2,...,Nike_Shoe_Size22,Nike_Shoe_Size23,Nike_Shoe_Size24,Nike_Shoe_Size25,gender,brand,colour1,colour2,colour3,colour4
0,Nike Air Force 1 '07 EasyOn,1,9695.00,UK 5.5,Style: FD1146-100,Awesome!! Fits really good very comfortable an...,4.6,https://www.nike.com/in/t/air-force-1-07-easyo...,UK 5.5,UK 6 (EU 39),...,_,_,_,_,women,Nike,White,White,White,None
1,Nike Air Force 1 '07 NN,1,9695.00,UK 2.5,Style: DV3808-101,Brought my usual size 4.1/2 true to size and c...,4.9,https://www.nike.com/in/t/air-force-1-07-nn-sh...,UK 2.5,UK 3,...,_,_,_,_,women,Nike,Summit White,Metallic Silver,Bronzine,None
2,Nike Dunk Low Twist,5,9695.00,UK 2.5,Style: DZ2794-100,Fits great and looks good . Bought it about 2 ...,4.6,https://www.nike.com/in/t/dunk-low-twist-shoes...,UK 2.5,UK 3,...,_,_,_,_,women,Nike,Coconut Milk,White,Vivid Sulphur,None
3,Nike Air Force 1 Shadow,1,11895.00,UK 2.5,Style: DZ1847-001,Love these trainers & love the colours and the...,5,https://www.nike.com/in/t/air-force-1-shadow-s...,UK 2.5,UK 3,...,_,_,_,_,women,Nike,Phantom,Pink Oxford,White,Red Stardust
4,Air Jordan 1 Low SE,1,10295.00,UK 2.5,Style: FN3722-801,"The color is gorgeous, I usually wear a 6.5 an...",4.8,https://www.nike.com/in/t/air-jordan-1-low-se-...,UK 2.5,UK 3,...,_,_,_,_,women,Nike,Sky J Orange,Sail,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,Sabrina 1 By You,1,13995.00,NaN,Style: FJ4036-900,_,_,https://www.nike.com/in/u/custom-sabrina-1-by-...,_,_,...,_,_,_,_,men,Nike,Multi-Colour,Multi-Colour,Multi-Colour,None
296,Nike Air Zoom Infinity Tour NEXT% Boa,1,17495.00,NaN,Style: DJ5590-103,Awesome but an air leak\nTrevorL410082050 - 18...,4.5,https://www.nike.com/in/t/air-zoom-infinity-to...,UK 5.5,UK 6 (EU 39),...,_,_,_,_,men,Nike,White,Photo Blue,Black,None
297,Nike SB Zoom Blazer Low Pro GT,3,6795.00,NaN,Style: DC7695-100,Shred ready yet casually comfirtable\nKeithS12...,4.9,https://www.nike.com/in/t/sb-zoom-blazer-low-p...,UK 5.5,UK 6 (EU 39),...,_,_,_,_,men,Nike,White,White,White,Black
298,LeBron Witness 8 EP,4,8695.00,NaN,Style: FB2237-100,_,0,https://www.nike.com/in/t/lebron-witness-8-ep-...,UK 6 (EU 40),UK 6.5,...,_,_,_,_,men,Nike,White,Light Smoke Grey,Black,None
299,Nike ISPA Universal,1,9695.00,NaN,Style: DM0886-200,These are a GO!\nCrossMose - 17 Nov 2023\nI re...,3,https://www.nike.com/in/t/ispa-universal-shoes...,UK 6 (EU 40),UK 7,...,_,_,_,_,men,Nike,Earth,Earth,None,None

In [25]:
Nike_Shoe.to_csv('Nike_Shoe.csv')

.

.

.

.

# Adidas Men

In [99]:
driver = webdriver.Chrome()
url = "https://www.adidas.com/"
driver.get(url)

In [32]:
search = driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div/header/div[2]/div/div[2]/div/input")
search.send_keys('shoes')
time.sleep(3)

In [33]:
search_button = driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div/header/div[2]/div/div[2]/div/div[2]/div/div[1]/div[2]/a[2]")
search_button.click()

In [37]:
adidas_Shoe_type = []  
adidas_Shoe_Name = []
adidas_Shoe_Number_of_colour = []
adidas_opening_url = []

In [38]:
page =1

for page in range(5):
        
        
        
    try:
        Type= driver.find_elements(By.XPATH,'//p[@class="glass-product-card__category"]')[:200]
        for ty in Type:
            adidas_Shoe_type.append(ty.text)
    except NoSuchElementException:
        adidas_Shoe_type.append('_')
       

    
    try:
        Name= driver.find_elements(By.XPATH,'//p[@class="glass-product-card__title"]')[:200]
        for na in Name:
            adidas_Shoe_Name.append(na.text)
    except NoSuchElementException:
        adidas_Shoe_Name.append('_')
    
    
    
    try:
        Number_of_colour= driver.find_elements(By.XPATH,'//p[@class="glass-product-card__label"]')[:200]
        for co in Number_of_colour:
            adidas_Shoe_Number_of_colour.append(co.text)
    except NoSuchElementException:
        adidas_Shoe_Number_of_colour.append('_')
    

        
    url = driver.find_elements(By.XPATH,'//a[@class="glass-product-card__assets-link"]')[:200]
    for i in url:
        adidas_opening_url.append(i.get_attribute('href')) 
    
    next_button = driver.find_element(By.XPATH,'//a[@data-auto-id="plp-pagination-next"]')
    next_button.click()
    time.sleep(90)
    
    page +=1

In [39]:
print(len(adidas_Shoe_type),
     len(adidas_Shoe_Name),
     len(adidas_Shoe_Number_of_colour),
     len(adidas_opening_url))

240 240 240 240

In [40]:
adidas_Shoe_Men1 = pd.DataFrame({'adidas_Shoe_Name':adidas_Shoe_Name[:200],'adidas_Shoe_type':adidas_Shoe_type[:200],'adidas_Shoe_Number_of_colour':adidas_Shoe_Number_of_colour[:200],'adidas_opening_url':adidas_opening_url[:200]})
adidas_Shoe_Men1

,adidas_Shoe_Name,adidas_Shoe_type,adidas_Shoe_Number_of_colour,adidas_opening_url
0,Superstar Shoes,Men originals,2 colours,https://www.adidas.co.in/superstar-shoes/GW217...
1,Superstar Shoes,originals,3 colours,https://www.adidas.co.in/superstar-shoes/EG495...
2,Samba OG Shoes,originals,4 colours,https://www.adidas.co.in/samba-og-shoes/B75807...
3,Samba OG Shoes,originals,4 colours,https://www.adidas.co.in/samba-og-shoes/B75806...
4,Superstar Shoes,Men originals,3 colours,https://www.adidas.co.in/superstar-shoes/EG495...
...,...,...,...,...
195,Duramo SL Shoes,Men Running,5 colours · win race,https://www.adidas.co.in/duramo-sl-shoes/IE969...
196,Response Runner Shoes,Running,3 colours,https://www.adidas.co.in/response-runner-shoes...
197,Gazelle Shoes,Men Lifestyle,3 colours,https://www.adidas.co.in/gazelle-shoes/GX9882....
198,VL Court 3.0 Shoes,Men sportswear,2 colours · online exclusive,https://www.adidas.co.in/vl-court-3.0-shoes/ID...
199,Adilette Comfort Adjustable Bandage Slides,sportswear,2 colours,https://www.adidas.co.in/adilette-comfort-adju...

In [41]:
adidas_Shoe_Men1.to_csv('adidas_Shoe_Men1.csv')

In [100]:
adidas_Shoe_Men1 = pd.read_csv('adidas_Shoe_Men1.csv')

In [101]:
adidas_opening_url = adidas_Shoe_Men1['adidas_opening_url']
adidas_Shoe_Name = adidas_Shoe_Men1['adidas_Shoe_Name']
adidas_Shoe_type = adidas_Shoe_Men1['adidas_Shoe_type']
adidas_Shoe_Number_of_colour = adidas_Shoe_Men1['adidas_Shoe_Number_of_colour']

In [102]:
adidas_opening_url

0      https://www.adidas.co.in/superstar-shoes/GW217...
1      https://www.adidas.co.in/superstar-shoes/EG495...
2      https://www.adidas.co.in/samba-og-shoes/B75807...
3      https://www.adidas.co.in/samba-og-shoes/B75806...
4      https://www.adidas.co.in/superstar-shoes/EG495...
                             ...
195    https://www.adidas.co.in/duramo-sl-shoes/IE969...
196    https://www.adidas.co.in/response-runner-shoes...
197    https://www.adidas.co.in/gazelle-shoes/GX9882....
198    https://www.adidas.co.in/vl-court-3.0-shoes/ID...
199    https://www.adidas.co.in/adilette-comfort-adju...
Name: adidas_opening_url, Length: 200, dtype: object

.

In [ ]:
# Even after half hour an the code keep running
req = requests.get("https://www.adidas.com/")
req

In [13]:
req = scraper.get("https://www.adidas.com/",headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"})
req

In [10]:
# No matter what i do this site doesn't let me scrape sizes it shows - 'Sorry, sizes couldn't load. Try reloading them below' and it kepton showin the same error

In [108]:
adidas_Shoe_colour = []
adidas_Shoe_Reviews = []
adidas_Shoe_Star_Rating = []
adidas_Shoe_original_price = []
adidas_Shoe_discounted_price = []
adidas_Shoe_Product_Code = []


adidas_Shoe_Size1=[]
adidas_Shoe_Size2=[]
adidas_Shoe_Size3=[]
adidas_Shoe_Size4=[]
adidas_Shoe_Size5=[]
adidas_Shoe_Size6=[]
adidas_Shoe_Size7=[]
adidas_Shoe_Size8=[]
adidas_Shoe_Size9=[]
adidas_Shoe_Size10=[]
adidas_Shoe_Size11=[]
adidas_Shoe_Size12=[]
adidas_Shoe_Size13=[]
adidas_Shoe_Size14=[]
adidas_Shoe_Size15=[]
adidas_Shoe_Size16=[]
adidas_Shoe_Size17=[]
adidas_Shoe_Size18=[]
adidas_Shoe_Size19=[]
adidas_Shoe_Size20=[]
adidas_Shoe_Size21=[]
adidas_Shoe_Size22=[]
adidas_Shoe_Size23=[]
adidas_Shoe_Size24=[]
adidas_Shoe_Size25=[]

In [ ]:
for p in adidas_opening_url:
    driver.get(p)
    time.sleep(10)
    
    
  
    try:
        price= driver.find_element(By.XPATH,'//div[@class="price___Z74_w price___35NVI gl-flex-col"]/div/div/div[1]')
        adidas_Shoe_original_price.append(price.text)
    except NoSuchElementException:
        adidas_Shoe_original_price.append('_')
        
        
    try:
        pric= driver.find_element(By.XPATH,'//div[@class="price___Z74_w price___35NVI gl-flex-col"]/div/div/div[2]')
        adidas_Shoe_discounted_price.append(pric.text)
    except NoSuchElementException:
        adidas_Shoe_discounted_price.append('_')
        
        
    try:
        colour = driver.find_element(By.XPATH,'//div[@class="sidebar-color-chooser___i7JXW"]/div[3]')
        adidas_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        adidas_Shoe_colour.append('_')


    try:
        Rating= driver.find_element(By.XPATH,'//div[@class="ratings-label-container___13pr-"]/span')
        adidas_Shoe_Star_Rating.append(Rating.text)
    except NoSuchElementException:
        adidas_Shoe_Star_Rating.append('_')
        
        
    try:
        dropp = driver.find_element(By.XPATH,'//div[@id="navigation-target-specifications"]')
        dropp.click()
        time.sleep(5)
        Code= driver.find_element(By.XPATH,'//ul[@class="gl-list"][2]/li[3]')
        adidas_Shoe_Product_Code.append(Code.text)
    except NoSuchElementException:
        adidas_Shoe_Product_Code.append('_')
        

            
    try:
        drop = driver.find_element(By.XPATH,'//div[@class="ratings-label-container___13pr-"]/span')
        drop.click()
        time.sleep(5)
        Reviews= driver.find_element(By.XPATH,'//div[@class="review___KFNQH"][1]/div[2]/div[1]')
        adidas_Shoe_Reviews.append(Reviews.text)
    except NoSuchElementException:
        adidas_Shoe_Reviews.append('_')

In [ ]:
# for some reason the size of shoes was not showing while i was opening adidas_opening_url it continued to show error and refresh option.
# i can see the sizes when i open it normally without selenium

In [15]:
len(adidas_Shoe_Reviews)

162

In [18]:
adidas_Shoe_Men2 = pd.DataFrame({'adidas_Shoe_Name':adidas_Shoe_Name[:160],'adidas_Shoe_original_price':adidas_Shoe_original_price[:160],'adidas_Shoe_discounted_price':adidas_Shoe_discounted_price[:160],'adidas_Shoe_type':adidas_Shoe_type[:160],'adidas_Shoe_Number_of_colour':adidas_Shoe_Number_of_colour[:160],'adidas_opening_url':adidas_opening_url[:160],'adidas_Shoe_colour':adidas_Shoe_colour[:160],'adidas_Shoe_Reviews':adidas_Shoe_Reviews[:160],'adidas_Shoe_Star_Rating':adidas_Shoe_Star_Rating[:160],'adidas_Shoe_Product_Code':adidas_Shoe_Product_Code[:160]})

In [19]:
adidas_Shoe_Men2['brand'] = 'adidas'
adidas_Shoe_Men2['gender'] = 'men'

In [20]:
adidas_Shoe_Men2.to_csv('adidas_Shoe_Men2.csv')

In [105]:
adidas_Shoe_Men2=pd.read_csv('adidas_Shoe_Men2.csv')

In [110]:
adidas_Shoe_Men2.head()

,Unnamed: 0,adidas_Shoe_Name,adidas_Shoe_original_price,adidas_Shoe_discounted_price,adidas_Shoe_type,adidas_Shoe_Number_of_colour,adidas_opening_url,adidas_Shoe_colour,adidas_Shoe_Reviews,adidas_Shoe_Star_Rating,adidas_Shoe_Product_Code,brand,gender
0,0,Superstar Shoes,₹12 999.00,₹6 499.50,Men originals,2 colours,https://www.adidas.co.in/superstar-shoes/GW217...,Sand Strata / Magic Beige / Legend Ink,"Beautiful and comfortable\nDecember 7, 2023",4.8,Product code: GW2176,adidas,men
1,1,Superstar Shoes,₹8 999.00,_,originals,3 colours,https://www.adidas.co.in/superstar-shoes/EG495...,Core Black / Cloud White / Core Black,"Best products\nDecember 12, 2023",4.8,Product code: EG4959,adidas,men
2,2,Samba OG Shoes,₹10 999.00,_,originals,4 colours,https://www.adidas.co.in/samba-og-shoes/B75807...,Core Black / Cloud White / Gum,"A quality shoe!\nDecember 12, 2023",4.7,Product code: B75807,adidas,men
3,3,Samba OG Shoes,₹11 999.00,_,originals,4 colours,https://www.adidas.co.in/samba-og-shoes/B75806...,Cloud White / Core Black / Clear Granite,"A quality shoe!\nDecember 12, 2023",4.7,Product code: B75806,adidas,men
4,4,Superstar Shoes,₹8 999.00,_,Men originals,3 colours,https://www.adidas.co.in/superstar-shoes/EG495...,Cloud White / Core Black / Cloud White,"Best products\nDecember 12, 2023",4.8,Product code: EG4958,adidas,men

.

.

# Adidas_women

In [12]:
driver = webdriver.Chrome()
driver.get("https://www.adidas.com/")

In [4]:
search = driver.find_element(By.XPATH,'//div[@class="_wrapper_1f3oz_1"]/input')
search.send_keys('women shoes')
time.sleep(3)

In [5]:
search_button = driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[2]/div/header/div[2]/div/div[2]/div/div[2]/div/div[1]/div[2]/a[1]/div[1]')
search_button.click()

In [6]:
adidas_Shoe_type = []  
adidas_Shoe_Name = []
adidas_Shoe_Number_of_colour = []
adidas_opening_url = []
adidas_Shoe_original_price = []

In [ ]:
page =1

for page in range(5):
    
    
  
    try:
        Type= driver.find_elements(By.XPATH,'//p[@class="glass-product-card__category"]')[:200]
        for ty in Type:
            adidas_Shoe_type.append(ty.text)
    except NoSuchElementException:
        adidas_Shoe_type.append('_')
       

    
    try:
        Name= driver.find_elements(By.XPATH,'//p[@class="glass-product-card__title"]')[:200]
        for na in Name:
            adidas_Shoe_Name.append(na.text)
    except NoSuchElementException:
        adidas_Shoe_Name.append('_')
    
    
    
    try:
        Number_of_colour= driver.find_elements(By.XPATH,'//p[@class="glass-product-card__label"]')[:200]
        for co in Number_of_colour:
            adidas_Shoe_Number_of_colour.append(co.text)
    except NoSuchElementException:
        adidas_Shoe_Number_of_colour.append('_')
    

        
    url = driver.find_elements(By.XPATH,'//a[@class="glass-product-card__assets-link"]')[:200]
    for i in url:
        adidas_opening_url.append(i.get_attribute('href')) 
    
    next_button = driver.find_element(By.XPATH,'//a[@data-auto-id="plp-pagination-next"]')
    next_button.click()
    time.sleep(90)
    
    page +=1

In [8]:
print(len(adidas_Shoe_type),
     len(adidas_Shoe_Name),
     len(adidas_Shoe_Number_of_colour),
     len(adidas_opening_url))

243 243 243 243

In [9]:
adidas_Shoe_women = pd.DataFrame({'adidas_Shoe_Name':adidas_Shoe_Name[:200],'adidas_Shoe_type':adidas_Shoe_type[:200],'adidas_Shoe_Number_of_colour':adidas_Shoe_Number_of_colour[:200],'adidas_opening_url':adidas_opening_url[:200]})
adidas_Shoe_women

,adidas_Shoe_Name,adidas_Shoe_type,adidas_Shoe_Number_of_colour,adidas_opening_url
0,Superstar Shoes,originals,2 colours,https://www.adidas.co.in/superstar-shoes/EG495...
1,Superstar Shoes,Women Lifestyle,,https://www.adidas.co.in/superstar-shoes/GY957...
2,Samba OG Shoes,originals,2 colours,https://www.adidas.co.in/samba-og-shoes/B75807...
3,Samba OG Shoes,originals,2 colours,https://www.adidas.co.in/samba-og-shoes/B75806...
4,Gazelle Shoes,originals,6 colours,https://www.adidas.co.in/gazelle-shoes/BB5478....
...,...,...,...,...
195,Y-3 Superstar,y_3,,https://www.adidas.co.in/y-3-superstar/IG0801....
196,Ultraboost Light GTX Shoes,Women Running,responsive run,https://www.adidas.co.in/ultraboost-light-gtx-...
197,Run 50s Shoes,Running,3 colours,https://www.adidas.co.in/run-50s-shoes/IG6554....
198,Gazelle 85 Shoes,Lifestyle,,https://www.adidas.co.in/gazelle-85-shoes/IE21...
199,Avryn Shoes,sportswear,2 colours,https://www.adidas.co.in/avryn-shoes/IG2372.html

In [10]:
adidas_Shoe_women.to_csv('adidas_Shoe_women.csv')

In [52]:
adidas_Shoe_women=pd.read_csv('adidas_Shoe_women.csv')

In [54]:
adidas_Shoe_women.columns

Index(['Unnamed: 0', 'adidas_Shoe_Name', 'adidas_Shoe_type',
       'adidas_Shoe_Number_of_colour', 'adidas_opening_url'],
      dtype='object')

In [55]:
adidas_Shoe_Name= adidas_Shoe_women['adidas_Shoe_Name']
adidas_Shoe_type= adidas_Shoe_women['adidas_Shoe_type']
adidas_Shoe_Number_of_colour= adidas_Shoe_women['adidas_Shoe_Number_of_colour']
adidas_opening_url= adidas_Shoe_women['adidas_opening_url']

In [14]:
adidas_opening_url=adidas_Shoe_women['adidas_opening_url']

.

In [42]:
adidas_Shoe_colour = []
adidas_Shoe_Reviews = []
adidas_Shoe_Star_Rating = []
adidas_Shoe_original_price = []
adidas_Shoe_discounted_price = []
adidas_Shoe_Product_Code = []

In [ ]:
for p in adidas_opening_url:
    driver.get(p)
    time.sleep(10)
    
    
  
    try:
        price= driver.find_element(By.XPATH,'//div[@class="price___Z74_w price___35NVI gl-flex-col"]/div/div/div[1]')
        adidas_Shoe_original_price.append(price.text)
    except NoSuchElementException:
        adidas_Shoe_original_price.append('_')
        
        
    try:
        pric= driver.find_element(By.XPATH,'//div[@class="price___Z74_w price___35NVI gl-flex-col"]/div/div/div[2]')
        adidas_Shoe_discounted_price.append(pric.text)
    except NoSuchElementException:
        adidas_Shoe_discounted_price.append('_')
        
        
    try:
        colour = driver.find_element(By.XPATH,'//div[@class="sidebar-color-chooser___i7JXW"]/div[3]')
        adidas_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        adidas_Shoe_colour.append('_')


    try:
        Rating= driver.find_element(By.XPATH,'//div[@class="ratings-label-container___13pr-"]/span')
        adidas_Shoe_Star_Rating.append(Rating.text)
    except NoSuchElementException:
        adidas_Shoe_Star_Rating.append('_')
        
        
    try:
        dropp = driver.find_element(By.XPATH,'//div[@id="navigation-target-specifications"]')
        dropp.click()
        time.sleep(5)
        Code= driver.find_element(By.XPATH,'//ul[@class="gl-list"][2]/li[3]')
        adidas_Shoe_Product_Code.append(Code.text)
    except NoSuchElementException:
        adidas_Shoe_Product_Code.append('_')
        

            
    try:
        drop = driver.find_element(By.XPATH,'//div[@class="ratings-label-container___13pr-"]/span')
        drop.click()
        time.sleep(5)
        Reviews= driver.find_element(By.XPATH,'//div[@class="review___KFNQH"][1]/div[2]/div[1]')
        adidas_Shoe_Reviews.append(Reviews.text)
    except NoSuchElementException:
        adidas_Shoe_Reviews.append('_')

In [56]:
adidas_Shoe_women2 = pd.DataFrame({'adidas_Shoe_Name':adidas_Shoe_Name[:145],'adidas_Shoe_original_price':adidas_Shoe_original_price[:145],'adidas_Shoe_discounted_price':adidas_Shoe_discounted_price[:145],'adidas_Shoe_type':adidas_Shoe_type[:145],'adidas_Shoe_Number_of_colour':adidas_Shoe_Number_of_colour[:145],'adidas_opening_url':adidas_opening_url[:145],'adidas_Shoe_colour':adidas_Shoe_colour[:145],'adidas_Shoe_Reviews':adidas_Shoe_Reviews[:145],'adidas_Shoe_Star_Rating':adidas_Shoe_Star_Rating[:145],'adidas_Shoe_Product_Code':adidas_Shoe_Product_Code[:145]})

In [58]:
adidas_Shoe_women2['brand'] = 'adidas'
adidas_Shoe_women2['gender'] = 'women'

In [59]:
adidas_Shoe_women2

,adidas_Shoe_Name,adidas_Shoe_original_price,adidas_Shoe_discounted_price,adidas_Shoe_type,adidas_Shoe_Number_of_colour,adidas_opening_url,adidas_Shoe_colour,adidas_Shoe_Reviews,adidas_Shoe_Star_Rating,adidas_Shoe_Product_Code,brand,gender
0,Superstar Shoes,₹8 999.00,_,originals,2 colours,https://www.adidas.co.in/superstar-shoes/EG495...,Core Black / Cloud White / Core Black,I am so happy to purchase the product I am gla...,4.8,Product code: EG4959,adidas,women
1,Superstar Shoes,₹8 999.00,₹4 499.50,Women Lifestyle,NaN,https://www.adidas.co.in/superstar-shoes/GY957...,_,"Genuine product\nNovember 29, 2023",4.6,Colour: Cloud White / Cloud White / Gold Metallic,adidas,women
2,Samba OG Shoes,₹10 999.00,_,originals,2 colours,https://www.adidas.co.in/samba-og-shoes/B75807...,Core Black / Cloud White / Gum,I would wear these to some on the go errands.\...,4.8,Product code: B75807,adidas,women
3,Samba OG Shoes,₹11 999.00,_,originals,2 colours,https://www.adidas.co.in/samba-og-shoes/B75806...,Cloud White / Core Black / Clear Granite,I would wear these to some on the go errands.\...,4.8,Product code: B75806,adidas,women
4,Gazelle Shoes,₹10 999.00,_,originals,6 colours,https://www.adidas.co.in/gazelle-shoes/BB5478....,Collegiate Navy / White / Gold Metallic,Stylish tribute using the classic adidas favor...,4.8,Colour: Collegiate Navy / White / Gold Metallic,adidas,women
...,...,...,...,...,...,...,...,...,...,...,...,...
140,Ultraboost Light Shoes,₹18 999.00,_,Running,15 colours,https://www.adidas.co.in/ultraboost-light-shoe...,Core Black / Grey Six / Cloud White,"Perfect for running !\nDecember 8, 2023",4.7,Continental™ Better Rubber outsole,adidas,women
141,Ultraboost Light 23 Shoes,₹18 999.00,_,Running,2 colours,https://www.adidas.co.in/ultraboost-light-23-s...,Core Black / Core Black / Lucid Lime,"Excellent comfort and fit.\nNovember 28, 2023",4.8,Continental™ Better Rubber outsole,adidas,women
142,Y-3 Kyasu Hi,₹37 999.00,_,Lifestyle,NaN,https://www.adidas.co.in/y-3-kyasu-hi/IF0750.html,_,_,_,_,adidas,women
143,Ultraboost 1.0 ATR Shoes,₹19 999.00,_,sportswear,2 colours,https://www.adidas.co.in/ultraboost-1.0-atr-sh...,Core Black / Carbon / Grey Six,It was wonderful everything was good and we ar...,4.0,Colour: Core Black / Carbon / Grey Six,adidas,women
144,4DFWD 3 Running Shoes,₹21 999.00,_,Women Running,7 colours,https://www.adidas.co.in/4dfwd-3-running-shoes...,Dash Grey S20 / Silver Violet S23 / Lucid Lemo...,"Super stable and well balanced.\nDecember 4, 2023",5.0,Contains a minimum of 20% recycled and renewab...,adidas,women

.

.

.

In [35]:
d=adidas_Shoe_women2['adidas_Shoe_original_price'].str.replace(' ','')
a=d.str.extract('(\d+)')
adidas_Shoe_women2['adidas_Shoe_original_price'] = a

xx=adidas_Shoe_women2['adidas_Shoe_discounted_price'].str.replace(' ','')
yy=xx.str.extract('(\d+)')
adidas_Shoe_women2['adidas_Shoe_discounted_price'] = yy

In [38]:
d=adidas_Shoe_Men2['adidas_Shoe_original_price'].str.replace(' ','')
a=d.str.extract('(\d+)')
adidas_Shoe_Men2['adidas_Shoe_original_price'] = a

xx=adidas_Shoe_Men2['adidas_Shoe_discounted_price'].str.replace(' ','')
yy=xx.str.extract('(\d+)')
adidas_Shoe_Men2['adidas_Shoe_discounted_price'] = yy

In [43]:
adidas_Shoe_Men2[['colour1','colour2','colour3']] = adidas_Shoe_Men2['adidas_Shoe_colour'].str.split('/',expand=True)

In [ ]:
adidas_Shoe_women2[['colour1','colour2','colour3','colour4']] = adidas_Shoe_women2['adidas_Shoe_colour'].str.split('/',expand=True)

In [45]:
adidas_Shoe = pd.concat([adidas_Shoe_women2,adidas_Shoe_Men2],ignore_index=True)
adidas_Shoe = adidas_Shoe.drop('Unnamed: 0',axis=1)

In [47]:
adidas_Shoe.head()

,adidas_Shoe_Name,adidas_Shoe_original_price,adidas_Shoe_discounted_price,adidas_Shoe_type,adidas_Shoe_Number_of_colour,adidas_opening_url,adidas_Shoe_Reviews,adidas_Shoe_Star_Rating,adidas_Shoe_Product_Code,brand,gender,colour1,colour2,colour3,colour4,adidas_Shoe_colour
0,Superstar Shoes,8999.0,NaN,originals,2 colours,https://www.adidas.co.in/superstar-shoes/EG495...,I am so happy to purchase the product I am gla...,4.8,Product code: EG4959,adidas,women,Core Black,Cloud White,Core Black,NaN,NaN
1,Superstar Shoes,8999.0,4499.0,Women Lifestyle,NaN,https://www.adidas.co.in/superstar-shoes/GY957...,"Genuine product\nNovember 29, 2023",4.6,Colour: Cloud White / Cloud White / Gold Metallic,adidas,women,_,NaN,NaN,NaN,NaN
2,Samba OG Shoes,10999.0,NaN,originals,2 colours,https://www.adidas.co.in/samba-og-shoes/B75807...,I would wear these to some on the go errands.\...,4.8,Product code: B75807,adidas,women,Core Black,Cloud White,Gum,NaN,NaN
3,Samba OG Shoes,11999.0,NaN,originals,2 colours,https://www.adidas.co.in/samba-og-shoes/B75806...,I would wear these to some on the go errands.\...,4.8,Product code: B75806,adidas,women,Cloud White,Core Black,Clear Granite,NaN,NaN
4,Gazelle Shoes,10999.0,NaN,originals,6 colours,https://www.adidas.co.in/gazelle-shoes/BB5478....,Stylish tribute using the classic adidas favor...,4.8,Colour: Collegiate Navy / White / Gold Metallic,adidas,women,Collegiate Navy,White,Gold Metallic,NaN,NaN

In [48]:
adidas_Shoe=adidas_Shoe.drop('adidas_Shoe_colour',axis=1)

In [50]:
adidas_Shoe.to_csv('adidas_Shoe.csv')

In [22]:
adidas_Shoe = pd.read_csv('adidas_Shoe.csv')

In [25]:
adidas_Shoe_women2 = adidas_Shoe[adidas_Shoe['gender']=='women']

In [26]:
adidas_Shoe_women2

,Unnamed: 0,adidas_Shoe_Name,adidas_Shoe_original_price,adidas_Shoe_discounted_price,adidas_Shoe_type,adidas_Shoe_Number_of_colour,adidas_opening_url,adidas_Shoe_Reviews,adidas_Shoe_Star_Rating,adidas_Shoe_Product_Code,brand,gender,colour1,colour2,colour3,colour4
0,0,Superstar Shoes,8999.0,NaN,originals,2 colours,https://www.adidas.co.in/superstar-shoes/EG495...,I am so happy to purchase the product I am gla...,4.8,Product code: EG4959,adidas,women,Core Black,Cloud White,Core Black,NaN
1,1,Superstar Shoes,8999.0,4499.0,Women Lifestyle,NaN,https://www.adidas.co.in/superstar-shoes/GY957...,"Genuine product\nNovember 29, 2023",4.6,Colour: Cloud White / Cloud White / Gold Metallic,adidas,women,_,NaN,NaN,NaN
2,2,Samba OG Shoes,10999.0,NaN,originals,2 colours,https://www.adidas.co.in/samba-og-shoes/B75807...,I would wear these to some on the go errands.\...,4.8,Product code: B75807,adidas,women,Core Black,Cloud White,Gum,NaN
3,3,Samba OG Shoes,11999.0,NaN,originals,2 colours,https://www.adidas.co.in/samba-og-shoes/B75806...,I would wear these to some on the go errands.\...,4.8,Product code: B75806,adidas,women,Cloud White,Core Black,Clear Granite,NaN
4,4,Gazelle Shoes,10999.0,NaN,originals,6 colours,https://www.adidas.co.in/gazelle-shoes/BB5478....,Stylish tribute using the classic adidas favor...,4.8,Colour: Collegiate Navy / White / Gold Metallic,adidas,women,Collegiate Navy,White,Gold Metallic,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,140,Ultraboost Light Shoes,18999.0,NaN,Running,15 colours,https://www.adidas.co.in/ultraboost-light-shoe...,"Perfect for running !\nDecember 8, 2023",4.7,Continental™ Better Rubber outsole,adidas,women,Core Black,Grey Six,Cloud White,NaN
141,141,Ultraboost Light 23 Shoes,18999.0,NaN,Running,2 colours,https://www.adidas.co.in/ultraboost-light-23-s...,"Excellent comfort and fit.\nNovember 28, 2023",4.8,Continental™ Better Rubber outsole,adidas,women,Core Black,Core Black,Lucid Lime,NaN
142,142,Y-3 Kyasu Hi,37999.0,NaN,Lifestyle,NaN,https://www.adidas.co.in/y-3-kyasu-hi/IF0750.html,_,_,_,adidas,women,_,NaN,NaN,NaN
143,143,Ultraboost 1.0 ATR Shoes,19999.0,NaN,sportswear,2 colours,https://www.adidas.co.in/ultraboost-1.0-atr-sh...,It was wonderful everything was good and we ar...,4.0,Colour: Core Black / Carbon / Grey Six,adidas,women,Core Black,Carbon,Grey Six,NaN
144,144,4DFWD 3 Running Shoes,21999.0,NaN,Women Running,7 colours,https://www.adidas.co.in/4dfwd-3-running-shoes...,"Super stable and well balanced.\nDecember 4, 2023",5.0,Contains a minimum of 20% recycled and renewab...,adidas,women,Dash Grey S20,Silver Violet S23,Lucid Lemon F23,NaN

In [60]:
driver.close()

.

.

# Puma

In [58]:
driver = webdriver.Chrome()
driver.get("https://us.puma.com/us/en")
time.sleep(10)

In [59]:
search1 = driver.find_element(By.XPATH,'//button[@data-test-id="search-icon-nav"]')
search1.click()
time.sleep(3)
search2 = driver.find_element(By.XPATH,'//input[@class="w-full h-14 rounded-sm border-1 focus-within:ring bg-neutral-0 text-neutral-100 border-neutral-60 hover:border-neutral-100 focus-within:border-neutral-100 pl-4 pr-14 rtl:pr-4 rtl:pl-14"]')
search2.send_keys('men shoes')
search3 = driver.find_element(By.XPATH,'//button[@data-test-id="search-flyout-form-submit"]')
search3.click()

In [65]:
puma_Shoe_Name = []
puma_Shoe_Number_of_colour = []
opening_url = []

In [66]:
i = 0
while(i<150):
    driver.execute_script("window.scrollBy(0,200)")
    i+=1
    time.sleep(3)


try:
    Name= driver.find_elements(By.XPATH,'//h3[@class="w-full mobile:text-sm mobile:pr-0 font-bold text-base pr-5 line-clamp-2"]')[:200]
    for na in Name:
        puma_Shoe_Name.append(na.text)
except NoSuchElementException:
    puma_Shoe_Name.append('_')
    
    

try:
    Number_of_colour= driver.find_elements(By.XPATH,'//span[@class="group-hover:hidden group-focus-within:hidden text-puma-black-300 uppercase text-xs whitespace-nowrap"or@class="text-puma-black-300 uppercase text-xs whitespace-nowrap"]')[:200]
    for co in Number_of_colour:
        puma_Shoe_Number_of_colour.append(co.text)
except NoSuchElementException:
    puma_Shoe_Number_of_colour.append('_')
    

   
url = driver.find_elements(By.XPATH,'//a[@class="tw-hqslau tw-xbcb1y"and@data-test-id="product-list-item-link"]')[:200]
for i in url:
    opening_url.append(i.get_attribute('href'))

In [67]:
print(
len(puma_Shoe_Name),
len(puma_Shoe_Number_of_colour),
len(opening_url))

200 200 200

In [68]:
puma_Shoe_Men = pd.DataFrame({'puma_Shoe_Name':puma_Shoe_Name[:180],'puma_Shoe_Number_of_colour':puma_Shoe_Number_of_colour[:180],'opening_url':opening_url[:180]})
puma_Shoe_Men

,puma_Shoe_Name,puma_Shoe_Number_of_colour,opening_url
0,Viz Runner Repeat Men's Running Sneakers\nPuma...,4 COLORS,https://us.puma.com/us/en/pd/viz-runner-repeat...
1,Axelion NXT Men's Running Shoes\nPuma Black-Ur...,3 COLORS,https://us.puma.com/us/en/pd/axelion-nxt-mens-...
2,Redon Bungee Shoes\nPuma White-Puma White-Puma...,2 COLORS,https://us.puma.com/us/en/pd/redon-bungee-shoe...
3,Contempt Demi Men's Training Shoes\nPuma Black...,4 COLORS,https://us.puma.com/us/en/pd/contempt-demi-men...
4,PUMA Serve Pro Men's Sneakers\nPuma Black-Puma...,2 COLORS,https://us.puma.com/us/en/pd/puma-serve-pro-me...
...,...,...,...
175,Court Rider Chaos Team Men's Basketball Shoes\...,2 COLORS,https://us.puma.com/us/en/pd/court-rider-chaos...
176,C-Rey Sneakers SD\nPutty-Puma White-Puma White,2 COLORS,https://us.puma.com/us/en/pd/c-rey-sneakers-sd...
177,Future Rider Camo Flagship Men's Sneakers\nTap...,2 COLORS,https://us.puma.com/us/en/pd/future-rider-camo...
178,Vis2k 2000s Men's Sneakers\nPUMA Navy-PUMA Whi...,1 COLOR,https://us.puma.com/us/en/pd/vis2k-2000s-mens-...
179,Triple Mid Basketball Shoes\nPuma White-Puma B...,1 COLOR,https://us.puma.com/us/en/pd/triple-mid-basket...

In [69]:
puma_Shoe_Men.to_csv('puma_Shoe_Men.csv')

In [70]:
puma_Shoe_Men = pd.read_csv('puma_Shoe_Men.csv')

In [71]:
opening_url = puma_Shoe_Men['opening_url']

In [83]:
puma_Shoe_original_price = []
puma_Shoe_discounted_price = []
puma_Shoe_colour = []
puma_Shoe_Product_Code = []
puma_Shoe_Reviews = []
puma_Shoe_Star_Rating = []



puma_Shoe_Size1=[]
puma_Shoe_Size2=[]
puma_Shoe_Size3=[]
puma_Shoe_Size4=[]
puma_Shoe_Size5=[]
puma_Shoe_Size6=[]
puma_Shoe_Size7=[]
puma_Shoe_Size8=[]
puma_Shoe_Size9=[]
puma_Shoe_Size10=[]
puma_Shoe_Size11=[]
puma_Shoe_Size12=[]
puma_Shoe_Size13=[]
puma_Shoe_Size14=[]
puma_Shoe_Size15=[]
puma_Shoe_Size16=[]
puma_Shoe_Size17=[]
puma_Shoe_Size18=[]
puma_Shoe_Size19=[]
puma_Shoe_Size20=[]
puma_Shoe_Size21=[]
puma_Shoe_Size22=[]
puma_Shoe_Size23=[]
puma_Shoe_Size24=[]
puma_Shoe_Size25=[]

In [84]:
for p in opening_url:
    driver.get(p)
    time.sleep(8)
       
    try:
        size1= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[1]/span')
        puma_Shoe_Size1.append(size1.text)
    except NoSuchElementException:
        puma_Shoe_Size1.append('_')

    try:
        size2= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[2]/span')
        puma_Shoe_Size2.append(size2.text)
    except NoSuchElementException:
        puma_Shoe_Size2.append('_')
        
    try:
        size3= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[3]/span')
        puma_Shoe_Size3.append(size3.text)
    except NoSuchElementException:
        puma_Shoe_Size3.append('_')
        
    try:
        size4= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[4]/span')
        puma_Shoe_Size4.append(size4.text)
    except NoSuchElementException:
        puma_Shoe_Size4.append('_')
        
    try:
        size5= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[5]/span')
        puma_Shoe_Size5.append(size5.text)
    except NoSuchElementException:
        puma_Shoe_Size5.append('_')
        
    try:
        size6= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[6]/span')
        puma_Shoe_Size6.append(size6.text)
    except NoSuchElementException:
        puma_Shoe_Size6.append('_')
        
    try:
        size7= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[7]/span')
        puma_Shoe_Size7.append(size7.text)
    except NoSuchElementException:
        puma_Shoe_Size7.append('_')
        
    try:
        size8= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[8]/span')
        puma_Shoe_Size8.append(size8.text)
    except NoSuchElementException:
        puma_Shoe_Size8.append('_')
        
    try:
        size9= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[9]/span')
        puma_Shoe_Size9.append(size9.text)
    except NoSuchElementException:
        puma_Shoe_Size9.append('_')
        
    try:
        size10= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[10]/span')
        puma_Shoe_Size10.append(size10.text)
    except NoSuchElementException:
        puma_Shoe_Size10.append('_')
        
    try:
        size11= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[11]/span')
        puma_Shoe_Size11.append(size11.text)
    except NoSuchElementException:
        puma_Shoe_Size11.append('_')
        
    try:
        size12= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[12]/span')
        puma_Shoe_Size12.append(size12.text)
    except NoSuchElementException:
        puma_Shoe_Size12.append('_')
        
    try:
        size13= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[13]/span')
        puma_Shoe_Size13.append(size13.text)
    except NoSuchElementException:
        puma_Shoe_Size13.append('_')
        
    try:
        size14= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[14]/span')
        puma_Shoe_Size14.append(size14.text)
    except NoSuchElementException:
        puma_Shoe_Size14.append('_')
        
    try:
        size15= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[15]/span')
        puma_Shoe_Size15.append(size15.text)
    except NoSuchElementException:
        puma_Shoe_Size15.append('_')
        
    try:
        size16= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[16]/span')
        puma_Shoe_Size16.append(size16.text)
    except NoSuchElementException:
        puma_Shoe_Size16.append('_')
        
    try:
        size17= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[17]/span')
        puma_Shoe_Size17.append(size17.text)
    except NoSuchElementException:
        puma_Shoe_Size17.append('_')
        
    try:
        size18= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[18]/span')
        puma_Shoe_Size18.append(size18.text)
    except NoSuchElementException:
        puma_Shoe_Size18.append('_')
        
    try:
        size19= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[19]/span')
        puma_Shoe_Size19.append(size19.text)
    except NoSuchElementException:
        puma_Shoe_Size19.append('_')
        
    try:
        size20= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[20]/span')
        puma_Shoe_Size20.append(size20.text)
    except NoSuchElementException:
        puma_Shoe_Size20.append('_')
        
    try:
        size21= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[21]/span')
        puma_Shoe_Size21.append(size21.text)
    except NoSuchElementException:
        puma_Shoe_Size21.append('_')
        
    try:
        size22= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[22]/span')
        puma_Shoe_Size22.append(size22.text)
    except NoSuchElementException:
        puma_Shoe_Size22.append('_')
        
    try:
        size23= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[23]/span')
        puma_Shoe_Size23.append(size23.text)
    except NoSuchElementException:
        puma_Shoe_Size23.append('_')
        
    try:
        size24= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[24]/span')
        puma_Shoe_Size24.append(size24.text)
    except NoSuchElementException:
        puma_Shoe_Size24.append('_')
        
    try:
        size25= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[25]/span')
        puma_Shoe_Size25.append(size25.text)
    except NoSuchElementException:
        puma_Shoe_Size25.append('_')
        
        
        
        
        
    try:
        colour= driver.find_element(By.XPATH,'//h4[@class="tw-6ypl7n tw-lxvy65 tw-6nh9ql tw-p9uz4a tw-1h4nwdw"]')
        puma_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        puma_Shoe_colour.append('_')
    
    try:
        Product_Code= driver.find_element(By.XPATH,'//ul[@class="tw-1h4nwdw tw-p9uz4a tw-xwzea6 list-disc list-inside"]/li[1]')
        puma_Shoe_Product_Code.append(Product_Code.text)
    except NoSuchElementException:
        puma_Shoe_Product_Code.append('_')
            

    try:
        Rating= driver.find_element(By.XPATH,'//div[@class="tw-1uc1ku0 tw-1p4ksvz"][1]/div[1]')
        puma_Shoe_Star_Rating.append(Rating.text)
    except NoSuchElementException:
        puma_Shoe_Star_Rating.append('_')
        
        
    try:
        original= driver.find_element(By.XPATH,'//span[@class="whitespace-nowrap text-base font-bold override:md:text-2xl override:opacity-100" or @class="whitespace-nowrap text-base line-through opacity-50 override:font-bold override:opacity-100"]')
        puma_Shoe_original_price.append(original.text)
    except NoSuchElementException:
        puma_Shoe_original_price.append('_')
        
    try:
        discounted= driver.find_element(By.XPATH,'//div[@class="tw-qlq5hv tw-1p4ksvz"]/span[1]')
        puma_Shoe_discounted_price.append(discounted.text)
    except NoSuchElementException:
        puma_Shoe_discounted_price.append('_')
        
    try:
        drop = driver.find_element(By.XPATH,'//button[@class="group tw-19fr0v0 tw-ozwx86 flex-row after::absolute after::hidden after::pointer-events-none after::-left-1 after::-top-1 after::-right-1 after::-bottom-1 after::border-2 after::border-outline after::rounded-sm tw-10skrdm self-end"][2]')
        drop.click()
        time.sleep(8)
        Reviews= driver.find_element(By.XPATH,'//article[@class="pt-5 border-t"][1]/div[2]/p')
        puma_Shoe_Reviews.append(Reviews.text)
    except NoSuchElementException:
        puma_Shoe_Reviews.append('_')

KeyboardInterrupt

In [90]:
puma_Shoe_men=pd.DataFrame({
'puma_Shoe_Name':puma_Shoe_Name[:135],

'puma_Shoe_original_price':puma_Shoe_original_price[:135], 
'puma_Shoe_discounted_price':puma_Shoe_discounted_price[:135],
'puma_Shoe_colour':puma_Shoe_colour[:135],
'puma_Shoe_Number_of_colour':puma_Shoe_Number_of_colour[:135],
'puma_Shoe_Product_Code':puma_Shoe_Product_Code[:135],
'puma_Shoe_Reviews':puma_Shoe_Reviews[:135],
'puma_Shoe_Star_Rating':puma_Shoe_Star_Rating[:135],

'puma_Shoe_Size1':puma_Shoe_Size1[:135],
'puma_Shoe_Size2':puma_Shoe_Size2[:135],
'puma_Shoe_Size3':puma_Shoe_Size3[:135],
'puma_Shoe_Size4':puma_Shoe_Size4[:135],
'puma_Shoe_Size5':puma_Shoe_Size5[:135],
'puma_Shoe_Size6':puma_Shoe_Size6[:135],
'puma_Shoe_Size7':puma_Shoe_Size7[:135],
'puma_Shoe_Size8':puma_Shoe_Size8[:135],
'puma_Shoe_Size9':puma_Shoe_Size9[:135],
'puma_Shoe_Size10':puma_Shoe_Size10[:135],
'puma_Shoe_Size11':puma_Shoe_Size11[:135],
'puma_Shoe_Size12':puma_Shoe_Size12[:135],
'puma_Shoe_Size13':puma_Shoe_Size13[:135],
'puma_Shoe_Size14':puma_Shoe_Size14[:135],
'puma_Shoe_Size15':puma_Shoe_Size15[:135],
'puma_Shoe_Size16':puma_Shoe_Size16[:135],
'puma_Shoe_Size17':puma_Shoe_Size17[:135],
'puma_Shoe_Size18':puma_Shoe_Size18[:135],
'puma_Shoe_Size19':puma_Shoe_Size19[:135],
'puma_Shoe_Size20':puma_Shoe_Size20[:135],
'puma_Shoe_Size21':puma_Shoe_Size21[:135],
'puma_Shoe_Size22':puma_Shoe_Size22[:135],
'puma_Shoe_Size23':puma_Shoe_Size23[:135],
'puma_Shoe_Size24':puma_Shoe_Size24[:135],
'puma_Shoe_Size25':puma_Shoe_Size25[:135],
'opening_url':opening_url[:135]})

In [94]:
puma_Shoe_men.to_csv('puma_Shoe_men2.csv')

In [26]:
puma_Shoe_men2 =pd.read_csv('puma_Shoe_men2.csv')

In [28]:
puma_Shoe_men2['gender'] = 'men'
puma_Shoe_men2['brand'] = 'Puma'
puma_Shoe_men2

,Unnamed: 0,puma_Shoe_Name,puma_Shoe_original_price,puma_Shoe_discounted_price,puma_Shoe_colour,puma_Shoe_Number_of_colour,puma_Shoe_Product_Code,puma_Shoe_Reviews,puma_Shoe_Star_Rating,puma_Shoe_Size1,...,puma_Shoe_Size19,puma_Shoe_Size20,puma_Shoe_Size21,puma_Shoe_Size22,puma_Shoe_Size23,puma_Shoe_Size24,puma_Shoe_Size25,opening_url,gender,brand
0,0,Viz Runner Repeat Men's Running Sneakers\nPuma...,$65.00,$32.50,Puma Black-Puma White,4 COLORS,Style: 377333_02,Really satisfied and excellent quality. Still ...,Average: 4.2 / 5,Size\n7,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/viz-runner-repeat...,men,Puma
1,1,Axelion NXT Men's Running Shoes\nPuma Black-Ur...,$80.00,$40.00,Puma Black-Urban Red,3 COLORS,Style: 195656_01,I love then. Natural fit. Very comfortable. I’...,Average: 4.3 / 5,Size\n7,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/axelion-nxt-mens-...,men,Puma
2,2,Redon Bungee Shoes\nPuma White-Puma White-Puma...,$60.00,$30.00,Puma White-Puma White-Puma Black,2 COLORS,Style: 388167_01,I just received my shoes and Im impressed abou...,Average: 4.0 / 5,Size\n7,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/redon-bungee-shoe...,men,Puma
3,3,Contempt Demi Men's Training Shoes\nPuma Black...,$65.00,$32.50,Puma Black-Asphalt,4 COLORS,Style: 193160_01,Great quality and super lightweight. Very sati...,Average: 4.0 / 5,Size\n7,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/contempt-demi-men...,men,Puma
4,4,PUMA Serve Pro Men's Sneakers\nPuma Black-Puma...,$65.00,$32.50,Puma Black-Puma Black-Puma White-Puma Team Gold,2 COLORS,Style: 380188_04,Very comfortable sneaker…would definitely reco...,Average: 3.8 / 5,Size\n7,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/puma-serve-pro-me...,men,Puma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,130,PUMA x FIRST MILE Electrify NITRO™ 3 Men's Run...,$110.00,$110.00,PUMA Black-Astro Red-Alpine Snow,1 COLOR,Style: 378457_01,_,$110.00\nOr 4 payments of $27.50 by\nAfterpay\...,Size\n7,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/puma-x-first-mile...,men,Puma
131,131,Court Rider Chaos Slash Men's Basketball Shoes...,$100.00,$74.99,Neon Sun-PUMA Black,3 COLORS,Style: 378052_08,I bought these shoes a few months ago because ...,Average: 4.8 / 5,Size\n7,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/court-rider-chaos...,men,Puma
132,132,Velocity NITRO™ 2 Men's Running Shoes\nUltra B...,$120.00,$120.00,Ultra Blue-Fire Orchid,3 COLORS,Style: 195337_19,"As a forefoot runner, with wide feet, and a pr...",Average: 4.4 / 5,Size\n7,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/velocity-nitro%E2...,men,Puma
133,133,Mercedes-AMG Petronas Motorsport Carbon Cat Me...,$110.00,$82.99,PUMA Black-Spectra Green,1 COLOR,Style: 307542_02,Website photo is looking perfect and glamorous...,$82.99\n$110.00\nOr 4 payments of $20.75 by\nA...,Size\n4,...,Size\n14,_,_,_,_,_,_,https://us.puma.com/us/en/pd/mercedes-amg-petr...,men,Puma
134,134,Viz Runner Repeat Men's Running Sneakers\nPUMA...,$65.00,$32.50,PUMA White-Ultra Orange,4 COLORS,Style: 377333_10,Really satisfied and excellent quality. Still ...,Average: 4.2 / 5,Size\n7,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/viz-runner-repeat...,men,Puma

In [29]:
puma_Shoe_men2.to_csv('puma_Shoe_men2.csv')

In [98]:
driver.close()

.

.

.

# women

In [4]:
driver = webdriver.Chrome()
driver.get("https://us.puma.com/us/en")
time.sleep(10)

In [6]:
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

WebDriverWait(driver,15).until(EC.element_to_be_clickable((By.XPATH,'//button[@data-test-id="search-icon-nav"]')))
search1 = driver.find_element(By.XPATH,'//button[@data-test-id="search-icon-nav"]')
search1.click()
time.sleep(3)
search2 = driver.find_element(By.XPATH,'//input[@class="w-full h-14 rounded-sm border-1 focus-within:ring bg-neutral-0 text-neutral-100 border-neutral-60 hover:border-neutral-100 focus-within:border-neutral-100 pl-4 pr-14 rtl:pr-4 rtl:pl-14"]')
search2.send_keys('women shoes')
search3 = driver.find_element(By.XPATH,'//button[@data-test-id="search-flyout-form-submit"]')
search3.click()

In [7]:
# ElementClickInterceptedException

In [8]:
puma_Shoe_Name = []
puma_Shoe_Number_of_colour = []
opening_url = []

In [ ]:
i = 0
while(i<150):
    driver.execute_script("window.scrollBy(0,200)")
    i+=1
    time.sleep(3)

In [9]:




try:
    Name= driver.find_elements(By.XPATH,'//h3[@class="w-full mobile:text-sm mobile:pr-0 font-bold text-base pr-5 line-clamp-2"]')[:120]
    for na in Name:
        puma_Shoe_Name.append(na.text)
except NoSuchElementException:
    puma_Shoe_Name.append('_')
    
    

try:
    Number_of_colour= driver.find_elements(By.XPATH,'//span[@class="group-hover:hidden group-focus-within:hidden text-puma-black-300 uppercase text-xs whitespace-nowrap"or@class="text-puma-black-300 uppercase text-xs whitespace-nowrap"]')[:120]
    for co in Number_of_colour:
        puma_Shoe_Number_of_colour.append(co.text)
except NoSuchElementException:
    puma_Shoe_Number_of_colour.append('_')
    

   
url = driver.find_elements(By.XPATH,'//a[@class="tw-hqslau tw-xbcb1y"and@data-test-id="product-list-item-link"]')[:120]
for i in url:
    opening_url.append(i.get_attribute('href'))

In [10]:
puma_Shoe_women1 = pd.DataFrame({'puma_Shoe_Name':puma_Shoe_Name[:120],'puma_Shoe_Number_of_colour':puma_Shoe_Number_of_colour[:120],'opening_url':opening_url[:120]})
puma_Shoe_women1

,puma_Shoe_Name,puma_Shoe_Number_of_colour,opening_url
0,Star Vital Women's Training Shoes\nPUMA Black-...,2 COLORS,https://us.puma.com/us/en/pd/star-vital-womens...
1,Better Foam Prowl Slip-On Wide Women's Trainin...,1 COLOR,https://us.puma.com/us/en/pd/better-foam-prowl...
2,Suede Classic XXI Women's Sneakers\nIcy Blue-P...,7 COLORS,https://us.puma.com/us/en/pd/suede-classic-xxi...
3,Ella Lace Up Women's Shoes\nPuma White-Puma Si...,2 COLORS,https://us.puma.com/us/en/pd/ella-lace-up-wome...
4,Star Vital Women's Training Shoes\nPuma Black-...,2 COLORS,https://us.puma.com/us/en/pd/star-vital-womens...
...,...,...,...
115,Mayze Classic Women's Sneakers\nPuma Black,2 COLORS,https://us.puma.com/us/en/pd/mayze-classic-wom...
116,Cassia SL Women's Sneakers\nPuma White-Puma Wh...,2 COLORS,https://us.puma.com/us/en/pd/cassia-sl-womens-...
117,Vis2K Women's Sneaker\nPUMA White-PUMA White,1 COLOR,https://us.puma.com/us/en/pd/vis2k-womens-snea...
118,Basket Classic Velvet Women's Sneakers\nMalach...,2 COLORS,https://us.puma.com/us/en/pd/basket-classic-ve...
119,Caina 2.0 Mid Lux Women's Sneakers\nAsphalt-As...,1 COLOR,https://us.puma.com/us/en/pd/caina-2-0-mid-lux...

In [11]:
puma_Shoe_women1.to_csv('puma_Shoe_women1.csv')

In [12]:
puma_Shoe_original_price = []
puma_Shoe_discounted_price = []
puma_Shoe_colour = []
puma_Shoe_Product_Code = []
puma_Shoe_Reviews = []
puma_Shoe_Star_Rating = []



puma_Shoe_Size1=[]
puma_Shoe_Size2=[]
puma_Shoe_Size3=[]
puma_Shoe_Size4=[]
puma_Shoe_Size5=[]
puma_Shoe_Size6=[]
puma_Shoe_Size7=[]
puma_Shoe_Size8=[]
puma_Shoe_Size9=[]
puma_Shoe_Size10=[]
puma_Shoe_Size11=[]
puma_Shoe_Size12=[]
puma_Shoe_Size13=[]
puma_Shoe_Size14=[]
puma_Shoe_Size15=[]
puma_Shoe_Size16=[]
puma_Shoe_Size17=[]
puma_Shoe_Size18=[]
puma_Shoe_Size19=[]
puma_Shoe_Size20=[]
puma_Shoe_Size21=[]
puma_Shoe_Size22=[]
puma_Shoe_Size23=[]
puma_Shoe_Size24=[]
puma_Shoe_Size25=[]

In [13]:
for p in opening_url:
    driver.get(p)
    time.sleep(15)
       
    try:
        size1= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[1]/span')
        puma_Shoe_Size1.append(size1.text)
    except NoSuchElementException:
        puma_Shoe_Size1.append('_')

    try:
        size2= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[2]/span')
        puma_Shoe_Size2.append(size2.text)
    except NoSuchElementException:
        puma_Shoe_Size2.append('_')
        
    try:
        size3= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[3]/span')
        puma_Shoe_Size3.append(size3.text)
    except NoSuchElementException:
        puma_Shoe_Size3.append('_')
        
    try:
        size4= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[4]/span')
        puma_Shoe_Size4.append(size4.text)
    except NoSuchElementException:
        puma_Shoe_Size4.append('_')
        
    try:
        size5= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[5]/span')
        puma_Shoe_Size5.append(size5.text)
    except NoSuchElementException:
        puma_Shoe_Size5.append('_')
        
    try:
        size6= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[6]/span')
        puma_Shoe_Size6.append(size6.text)
    except NoSuchElementException:
        puma_Shoe_Size6.append('_')
        
    try:
        size7= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[7]/span')
        puma_Shoe_Size7.append(size7.text)
    except NoSuchElementException:
        puma_Shoe_Size7.append('_')
        
    try:
        size8= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[8]/span')
        puma_Shoe_Size8.append(size8.text)
    except NoSuchElementException:
        puma_Shoe_Size8.append('_')
        
    try:
        size9= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[9]/span')
        puma_Shoe_Size9.append(size9.text)
    except NoSuchElementException:
        puma_Shoe_Size9.append('_')
        
    try:
        size10= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[10]/span')
        puma_Shoe_Size10.append(size10.text)
    except NoSuchElementException:
        puma_Shoe_Size10.append('_')
        
    try:
        size11= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[11]/span')
        puma_Shoe_Size11.append(size11.text)
    except NoSuchElementException:
        puma_Shoe_Size11.append('_')
        
    try:
        size12= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[12]/span')
        puma_Shoe_Size12.append(size12.text)
    except NoSuchElementException:
        puma_Shoe_Size12.append('_')
        
    try:
        size13= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[13]/span')
        puma_Shoe_Size13.append(size13.text)
    except NoSuchElementException:
        puma_Shoe_Size13.append('_')
        
    try:
        size14= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[14]/span')
        puma_Shoe_Size14.append(size14.text)
    except NoSuchElementException:
        puma_Shoe_Size14.append('_')
        
    try:
        size15= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[15]/span')
        puma_Shoe_Size15.append(size15.text)
    except NoSuchElementException:
        puma_Shoe_Size15.append('_')
        
    try:
        size16= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[16]/span')
        puma_Shoe_Size16.append(size16.text)
    except NoSuchElementException:
        puma_Shoe_Size16.append('_')
        
    try:
        size17= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[17]/span')
        puma_Shoe_Size17.append(size17.text)
    except NoSuchElementException:
        puma_Shoe_Size17.append('_')
        
    try:
        size18= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[18]/span')
        puma_Shoe_Size18.append(size18.text)
    except NoSuchElementException:
        puma_Shoe_Size18.append('_')
        
    try:
        size19= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[19]/span')
        puma_Shoe_Size19.append(size19.text)
    except NoSuchElementException:
        puma_Shoe_Size19.append('_')
        
    try:
        size20= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[20]/span')
        puma_Shoe_Size20.append(size20.text)
    except NoSuchElementException:
        puma_Shoe_Size20.append('_')
        
    try:
        size21= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[21]/span')
        puma_Shoe_Size21.append(size21.text)
    except NoSuchElementException:
        puma_Shoe_Size21.append('_')
        
    try:
        size22= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[22]/span')
        puma_Shoe_Size22.append(size22.text)
    except NoSuchElementException:
        puma_Shoe_Size22.append('_')
        
    try:
        size23= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[23]/span')
        puma_Shoe_Size23.append(size23.text)
    except NoSuchElementException:
        puma_Shoe_Size23.append('_')
        
    try:
        size24= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[24]/span')
        puma_Shoe_Size24.append(size24.text)
    except NoSuchElementException:
        puma_Shoe_Size24.append('_')
        
    try:
        size25= driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]/div/label[25]/span')
        puma_Shoe_Size25.append(size25.text)
    except NoSuchElementException:
        puma_Shoe_Size25.append('_')
        
        
        
        
        
    try:
        colour= driver.find_element(By.XPATH,'//h4[@class="tw-6ypl7n tw-lxvy65 tw-6nh9ql tw-p9uz4a tw-1h4nwdw"]')
        puma_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        puma_Shoe_colour.append('_')
    
    try:
        Product_Code= driver.find_element(By.XPATH,'//ul[@class="tw-1h4nwdw tw-p9uz4a tw-xwzea6 list-disc list-inside"]/li[1]')
        puma_Shoe_Product_Code.append(Product_Code.text)
    except NoSuchElementException:
        puma_Shoe_Product_Code.append('_')
            

    try:
        Rating= driver.find_element(By.XPATH,'//div[@class="tw-1uc1ku0 tw-1p4ksvz"][1]/div[1]')
        puma_Shoe_Star_Rating.append(Rating.text)
    except NoSuchElementException:
        puma_Shoe_Star_Rating.append('_')
        
        
    try:
        original= driver.find_element(By.XPATH,'//span[@class="whitespace-nowrap text-base font-bold override:md:text-2xl override:opacity-100" or @class="whitespace-nowrap text-base line-through opacity-50 override:font-bold override:opacity-100"]')
        puma_Shoe_original_price.append(original.text)
    except NoSuchElementException:
        puma_Shoe_original_price.append('_')
        
    try:
        discounted= driver.find_element(By.XPATH,'//div[@class="tw-qlq5hv tw-1p4ksvz"]/span[1]')
        puma_Shoe_discounted_price.append(discounted.text)
    except NoSuchElementException:
        puma_Shoe_discounted_price.append('_')
        
    try:
        drop = driver.find_element(By.XPATH,'//button[@class="group tw-19fr0v0 tw-ozwx86 flex-row after::absolute after::hidden after::pointer-events-none after::-left-1 after::-top-1 after::-right-1 after::-bottom-1 after::border-2 after::border-outline after::rounded-sm tw-10skrdm self-end"][2]')
        drop.click()
        time.sleep(8)
        Reviews= driver.find_element(By.XPATH,'//article[@class="pt-5 border-t"][1]/div[2]/p')
        puma_Shoe_Reviews.append(Reviews.text)
    except NoSuchElementException:
        puma_Shoe_Reviews.append('_')

In [14]:
len(puma_Shoe_Reviews)

120

In [16]:
puma_Shoe_women2=pd.DataFrame({
'puma_Shoe_Name':puma_Shoe_Name,

'puma_Shoe_original_price':puma_Shoe_original_price, 
'puma_Shoe_discounted_price':puma_Shoe_discounted_price,
'puma_Shoe_colour':puma_Shoe_colour,
'puma_Shoe_Number_of_colour':puma_Shoe_Number_of_colour,
'puma_Shoe_Product_Code':puma_Shoe_Product_Code,
'puma_Shoe_Reviews':puma_Shoe_Reviews,
'puma_Shoe_Star_Rating':puma_Shoe_Star_Rating,

'puma_Shoe_Size1':puma_Shoe_Size1,
'puma_Shoe_Size2':puma_Shoe_Size2,
'puma_Shoe_Size3':puma_Shoe_Size3,
'puma_Shoe_Size4':puma_Shoe_Size4,
'puma_Shoe_Size5':puma_Shoe_Size5,
'puma_Shoe_Size6':puma_Shoe_Size6,
'puma_Shoe_Size7':puma_Shoe_Size7,
'puma_Shoe_Size8':puma_Shoe_Size8,
'puma_Shoe_Size9':puma_Shoe_Size9,
'puma_Shoe_Size10':puma_Shoe_Size10,
'puma_Shoe_Size11':puma_Shoe_Size11,
'puma_Shoe_Size12':puma_Shoe_Size12,
'puma_Shoe_Size13':puma_Shoe_Size13,
'puma_Shoe_Size14':puma_Shoe_Size14,
'puma_Shoe_Size15':puma_Shoe_Size15,
'puma_Shoe_Size16':puma_Shoe_Size16,
'puma_Shoe_Size17':puma_Shoe_Size17,
'puma_Shoe_Size18':puma_Shoe_Size18,
'puma_Shoe_Size19':puma_Shoe_Size19,
'puma_Shoe_Size20':puma_Shoe_Size20,
'puma_Shoe_Size21':puma_Shoe_Size21,
'puma_Shoe_Size22':puma_Shoe_Size22,
'puma_Shoe_Size23':puma_Shoe_Size23,
'puma_Shoe_Size24':puma_Shoe_Size24,
'puma_Shoe_Size25':puma_Shoe_Size25,
'opening_url':opening_url})

In [17]:
puma_Shoe_women2['gender'] = 'women'
puma_Shoe_women2['brand'] = 'Puma'
puma_Shoe_women2

,puma_Shoe_Name,puma_Shoe_original_price,puma_Shoe_discounted_price,puma_Shoe_colour,puma_Shoe_Number_of_colour,puma_Shoe_Product_Code,puma_Shoe_Reviews,puma_Shoe_Star_Rating,puma_Shoe_Size1,puma_Shoe_Size2,...,puma_Shoe_Size19,puma_Shoe_Size20,puma_Shoe_Size21,puma_Shoe_Size22,puma_Shoe_Size23,puma_Shoe_Size24,puma_Shoe_Size25,opening_url,gender,brand
0,Star Vital Women's Training Shoes\nPUMA Black-...,$65.00,$32.50,PUMA Black-PUMA Silver,2 COLORS,Style: 194331_19,Love the look the comfort the style the price ...,Average: 4.3 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/star-vital-womens...,women,Puma
1,Better Foam Prowl Slip-On Wide Women's Trainin...,$65.00,$35.99,Puma Black-Puma Black,1 COLOR,Style: 376927_02,I purchase these abt 6 wks ago. The only compl...,Average: 3.9 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/better-foam-prowl...,women,Puma
2,Suede Classic XXI Women's Sneakers\nIcy Blue-P...,$75.00,$39.99,Icy Blue-PUMA White,7 COLORS,Style: 381410_85,These sneakers are cute and comfortable. They ...,Average: 4.3 / 5,Size\n6,Size\n6.5,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/suede-classic-xxi...,women,Puma
3,Ella Lace Up Women's Shoes\nPuma White-Puma Si...,$60.00,$30.00,Puma White-Puma Silver,2 COLORS,Style: 193919_01,First time buying Puma shoes and really glad I...,Average: 4.5 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/ella-lace-up-wome...,women,Puma
4,Star Vital Women's Training Shoes\nPuma Black-...,$65.00,$32.50,Puma Black-Rose Gold,2 COLORS,Style: 194331_15,Love the look the comfort the style the price ...,Average: 4.3 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/star-vital-womens...,women,Puma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Mayze Classic Women's Sneakers\nPuma Black,$90.00,$90.00,Puma Black,2 COLORS,Style: 384209_02,Très beau et confo par contre j'ai pris un .5 ...,Average: 3.9 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/mayze-classic-wom...,women,Puma
116,Cassia SL Women's Sneakers\nPuma White-Puma Wh...,$80.00,$42.99,Puma White-Puma White-Puma Team Gold,2 COLORS,Style: 385279_01,These run a half size small. After returning b...,Average: 3.6 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/cassia-sl-womens-...,women,Puma
117,Vis2K Women's Sneaker\nPUMA White-PUMA White,$85.00,$42.50,PUMA White-PUMA White,1 COLOR,Style: 395481_02,Great fit Goes with everything. Wipes off clea...,$42.50\n$85.00\nOr 4 payments of $10.63 by\nAf...,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/vis2k-womens-snea...,women,Puma
118,Basket Classic Velvet Women's Sneakers\nMalach...,$80.00,$64.99,Malachite-Puma Team Gold-PUMA White,2 COLORS,Style: 398949_01,_,BEST SELLER,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/basket-classic-ve...,women,Puma
119,Caina 2.0 Mid Lux Women's Sneakers\nAsphalt-As...,$75.00,$37.50,Asphalt-Asphalt-Puma Team Gold,1 COLOR,Style: 391236_01,Thus is a great purchase … lots of compliments...,$37.50\n$75.00\nOr 4 payments of $9.38 by\nAft...,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/caina-2-0-mid-lux...,women,Puma

In [18]:
puma_Shoe_women2.to_csv('puma_Shoe_women2.csv')

In [30]:
puma_Shoe_women2 = pd.read_csv('puma_Shoe_women2.csv')

In [21]:
puma_Shoe_men2=pd.read_csv('puma_Shoe_men2.csv')

In [ ]:
driver.close()

In [31]:
puma_Shoe = pd.concat([puma_Shoe_women2,puma_Shoe_men2],ignore_index=True)
puma_Shoe = puma_Shoe.drop('Unnamed: 0',axis=1)

puma_Shoe

,puma_Shoe_Name,puma_Shoe_original_price,puma_Shoe_discounted_price,puma_Shoe_colour,puma_Shoe_Number_of_colour,puma_Shoe_Product_Code,puma_Shoe_Reviews,puma_Shoe_Star_Rating,puma_Shoe_Size1,puma_Shoe_Size2,...,puma_Shoe_Size19,puma_Shoe_Size20,puma_Shoe_Size21,puma_Shoe_Size22,puma_Shoe_Size23,puma_Shoe_Size24,puma_Shoe_Size25,opening_url,gender,brand
0,Star Vital Women's Training Shoes\nPUMA Black-...,$65.00,$32.50,PUMA Black-PUMA Silver,2 COLORS,Style: 194331_19,Love the look the comfort the style the price ...,Average: 4.3 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/star-vital-womens...,women,Puma
1,Better Foam Prowl Slip-On Wide Women's Trainin...,$65.00,$35.99,Puma Black-Puma Black,1 COLOR,Style: 376927_02,I purchase these abt 6 wks ago. The only compl...,Average: 3.9 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/better-foam-prowl...,women,Puma
2,Suede Classic XXI Women's Sneakers\nIcy Blue-P...,$75.00,$39.99,Icy Blue-PUMA White,7 COLORS,Style: 381410_85,These sneakers are cute and comfortable. They ...,Average: 4.3 / 5,Size\n6,Size\n6.5,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/suede-classic-xxi...,women,Puma
3,Ella Lace Up Women's Shoes\nPuma White-Puma Si...,$60.00,$30.00,Puma White-Puma Silver,2 COLORS,Style: 193919_01,First time buying Puma shoes and really glad I...,Average: 4.5 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/ella-lace-up-wome...,women,Puma
4,Star Vital Women's Training Shoes\nPuma Black-...,$65.00,$32.50,Puma Black-Rose Gold,2 COLORS,Style: 194331_15,Love the look the comfort the style the price ...,Average: 4.3 / 5,Size\n5.5,Size\n6,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/star-vital-womens...,women,Puma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,PUMA x FIRST MILE Electrify NITRO™ 3 Men's Run...,$110.00,$110.00,PUMA Black-Astro Red-Alpine Snow,1 COLOR,Style: 378457_01,_,$110.00\nOr 4 payments of $27.50 by\nAfterpay\...,Size\n7,Size\n7.5,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/puma-x-first-mile...,men,Puma
251,Court Rider Chaos Slash Men's Basketball Shoes...,$100.00,$74.99,Neon Sun-PUMA Black,3 COLORS,Style: 378052_08,I bought these shoes a few months ago because ...,Average: 4.8 / 5,Size\n7,Size\n7.5,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/court-rider-chaos...,men,Puma
252,Velocity NITRO™ 2 Men's Running Shoes\nUltra B...,$120.00,$120.00,Ultra Blue-Fire Orchid,3 COLORS,Style: 195337_19,"As a forefoot runner, with wide feet, and a pr...",Average: 4.4 / 5,Size\n7,Size\n7.5,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/velocity-nitro%E2...,men,Puma
253,Mercedes-AMG Petronas Motorsport Carbon Cat Me...,$110.00,$82.99,PUMA Black-Spectra Green,1 COLOR,Style: 307542_02,Website photo is looking perfect and glamorous...,$82.99\n$110.00\nOr 4 payments of $20.75 by\nA...,Size\n4,Size\n4.5,...,Size\n14,_,_,_,_,_,_,https://us.puma.com/us/en/pd/mercedes-amg-petr...,men,Puma
254,Viz Runner Repeat Men's Running Sneakers\nPUMA...,$65.00,$32.50,PUMA White-Ultra Orange,4 COLORS,Style: 377333_10,Really satisfied and excellent quality. Still ...,Average: 4.2 / 5,Size\n7,Size\n7.5,...,_,_,_,_,_,_,_,https://us.puma.com/us/en/pd/viz-runner-repeat...,men,Puma

In [32]:
d=puma_Shoe['puma_Shoe_original_price'].str.replace(' ','')
a=d.str.extract('(\d+)')
puma_Shoe['puma_Shoe_original_price'] = a

In [33]:
xx=puma_Shoe['puma_Shoe_discounted_price'].str.replace(' ','')
yy=xx.str.extract('(\d+)')
puma_Shoe['puma_Shoe_discounted_price'] = yy

In [34]:
puma_Shoe[['colour1','colour2','colour3','colour4']] = puma_Shoe['puma_Shoe_colour'].str.split('-',expand=True)

In [35]:
puma_Shoe=puma_Shoe.drop('puma_Shoe_colour',axis=1)

In [36]:
puma_Shoe

,puma_Shoe_Name,puma_Shoe_original_price,puma_Shoe_discounted_price,puma_Shoe_Number_of_colour,puma_Shoe_Product_Code,puma_Shoe_Reviews,puma_Shoe_Star_Rating,puma_Shoe_Size1,puma_Shoe_Size2,puma_Shoe_Size3,...,puma_Shoe_Size23,puma_Shoe_Size24,puma_Shoe_Size25,opening_url,gender,brand,colour1,colour2,colour3,colour4
0,Star Vital Women's Training Shoes\nPUMA Black-...,65,32,2 COLORS,Style: 194331_19,Love the look the comfort the style the price ...,Average: 4.3 / 5,Size\n5.5,Size\n6,Size\n6.5,...,_,_,_,https://us.puma.com/us/en/pd/star-vital-womens...,women,Puma,PUMA Black,PUMA Silver,None,None
1,Better Foam Prowl Slip-On Wide Women's Trainin...,65,35,1 COLOR,Style: 376927_02,I purchase these abt 6 wks ago. The only compl...,Average: 3.9 / 5,Size\n5.5,Size\n6,Size\n6.5,...,_,_,_,https://us.puma.com/us/en/pd/better-foam-prowl...,women,Puma,Puma Black,Puma Black,None,None
2,Suede Classic XXI Women's Sneakers\nIcy Blue-P...,75,39,7 COLORS,Style: 381410_85,These sneakers are cute and comfortable. They ...,Average: 4.3 / 5,Size\n6,Size\n6.5,Size\n7,...,_,_,_,https://us.puma.com/us/en/pd/suede-classic-xxi...,women,Puma,Icy Blue,PUMA White,None,None
3,Ella Lace Up Women's Shoes\nPuma White-Puma Si...,60,30,2 COLORS,Style: 193919_01,First time buying Puma shoes and really glad I...,Average: 4.5 / 5,Size\n5.5,Size\n6,Size\n6.5,...,_,_,_,https://us.puma.com/us/en/pd/ella-lace-up-wome...,women,Puma,Puma White,Puma Silver,None,None
4,Star Vital Women's Training Shoes\nPuma Black-...,65,32,2 COLORS,Style: 194331_15,Love the look the comfort the style the price ...,Average: 4.3 / 5,Size\n5.5,Size\n6,Size\n6.5,...,_,_,_,https://us.puma.com/us/en/pd/star-vital-womens...,women,Puma,Puma Black,Rose Gold,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,PUMA x FIRST MILE Electrify NITRO™ 3 Men's Run...,110,110,1 COLOR,Style: 378457_01,_,$110.00\nOr 4 payments of $27.50 by\nAfterpay\...,Size\n7,Size\n7.5,Size\n8,...,_,_,_,https://us.puma.com/us/en/pd/puma-x-first-mile...,men,Puma,PUMA Black,Astro Red,Alpine Snow,None
251,Court Rider Chaos Slash Men's Basketball Shoes...,100,74,3 COLORS,Style: 378052_08,I bought these shoes a few months ago because ...,Average: 4.8 / 5,Size\n7,Size\n7.5,Size\n8,...,_,_,_,https://us.puma.com/us/en/pd/court-rider-chaos...,men,Puma,Neon Sun,PUMA Black,None,None
252,Velocity NITRO™ 2 Men's Running Shoes\nUltra B...,120,120,3 COLORS,Style: 195337_19,"As a forefoot runner, with wide feet, and a pr...",Average: 4.4 / 5,Size\n7,Size\n7.5,Size\n8,...,_,_,_,https://us.puma.com/us/en/pd/velocity-nitro%E2...,men,Puma,Ultra Blue,Fire Orchid,None,None
253,Mercedes-AMG Petronas Motorsport Carbon Cat Me...,110,82,1 COLOR,Style: 307542_02,Website photo is looking perfect and glamorous...,$82.99\n$110.00\nOr 4 payments of $20.75 by\nA...,Size\n4,Size\n4.5,Size\n5,...,_,_,_,https://us.puma.com/us/en/pd/mercedes-amg-petr...,men,Puma,PUMA Black,Spectra Green,None,None
254,Viz Runner Repeat Men's Running Sneakers\nPUMA...,65,32,4 COLORS,Style: 377333_10,Really satisfied and excellent quality. Still ...,Average: 4.2 / 5,Size\n7,Size\n7.5,Size\n8,...,_,_,_,https://us.puma.com/us/en/pd/viz-runner-repeat...,men,Puma,PUMA White,Ultra Orange,None,None

In [37]:
puma_Shoe.to_csv('puma_Shoe.csv')

In [38]:
puma_Shoe = pd.read_csv('puma_Shoe.csv')

In [39]:
puma_Shoe['puma_Shoe_original_price'] = puma_Shoe['puma_Shoe_original_price']*83
puma_Shoe['puma_Shoe_discounted_price'] = puma_Shoe['puma_Shoe_discounted_price']*83

In [40]:
puma_Shoe[['puma_Shoe_Star_Rating','puma_Shoe_Star_Rating2']] = puma_Shoe['puma_Shoe_Star_Rating'].str.split('/',expand=True)

In [41]:
d=puma_Shoe['puma_Shoe_Star_Rating'].str.replace(' ','')
a=d.str.extract('(\d+)')
puma_Shoe['puma_Shoe_Star_Rating'] = a

In [43]:
puma_Shoe = puma_Shoe.drop('puma_Shoe_Star_Rating2',axis=1)

In [44]:
puma_Shoe.to_csv('puma_Shoe1.csv')

.

.

.

# Skechers

In [54]:
ur= requests.get("https://www.skechers.com/search/?q=men+shoes&search-button=&lang=en_US")
ur

In [42]:
ur= requests.get("https://www.skechers.com/search/?q=men+shoes&search-button=&lang=en_US",headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"})
ur

In [4]:
driver = webdriver.Chrome()
driver.get("https://www.skechers.com")

In [6]:
search1 = driver.find_element(By.XPATH,'//a[@class="js-a-toggle"]')
search1.click()
time.sleep(3)

In [7]:
search2 = driver.find_element(By.XPATH,'/html/body/div[2]/header/nav[2]/div/div[2]/div/div/form/input[1]')
search2.send_keys('men shoes')
time.sleep(5)

In [8]:
search3 = driver.find_element(By.XPATH,'/html/body/div[2]/header/nav[2]/div/div[2]/div/div/form/button')
search3.click()

.

.

# Columbia

In [55]:
driver = webdriver.Chrome()
driver.get("https://www.columbia.com")

In [57]:
search1 = driver.find_element(By.XPATH,'//button[@class="no-flyout siteheader__search-link action__search js-action-search"]')
search1.click()
time.sleep(3)
search2 = driver.find_element(By.XPATH,'//input[@class="form-control search-field form-control-lg js-search-field"]')
search2.send_keys('men shoes')
search3 = driver.find_element(By.XPATH,'//button[@class="action__search--button js-action__search-submit"]')
search3.click()

#  After searching for men shoe when i try to crap data it refuse to let me do it .

.

.

# Woodland

# MEN

In [3]:
driver = webdriver.Chrome()
driver.get("https://www.woodlandworldwide.com")

In [9]:
search = driver.find_element(By.XPATH,'//a[@class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-umnham"][2]')
search.click()

In [20]:
woodland_Shoe_Name = []
opening_url = []

In [21]:
i = 0
while(i<150):
    driver.execute_script("window.scrollBy(0,200)")
    i+=1
    time.sleep(3)
    

try:
    Name= driver.find_elements(By.XPATH,'//p[@class="productcardplp_productname__F8lks"]')[:100]
    for na in Name:
        woodland_Shoe_Name.append(na.text)
except NoSuchElementException:
    woodland_Shoe_Name.append('_')
    

   
url = driver.find_elements(By.XPATH,'//a[@class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-15kjgm"]')[:100]
for i in url:
    opening_url.append(i.get_attribute('href'))

In [44]:
woodland_Shoe_men = pd.DataFrame({'woodland_Shoe_Name':woodland_Shoe_Name[:100],'opening_url':opening_url[:100]})
woodland_Shoe_men

,woodland_Shoe_Name,opening_url
0,Black Fabric Luxury Sports Shoes,https://www.woodlandworldwide.com/productinfo/...
1,Blue sneakers for men,https://www.woodlandworldwide.com/productinfo/...
2,White Fabric Luxury Sports Shoes,https://www.woodlandworldwide.com/productinfo/...
3,Beige Fabric Luxury Sports Shoes,https://www.woodlandworldwide.com/productinfo/...
4,Black Slip-on Sneaker,https://www.woodlandworldwide.com/productinfo/...
...,...,...
95,Grey sneakers for men,https://www.woodlandworldwide.com/productinfo/...
96,Olive/black sneakers for men,https://www.woodlandworldwide.com/productinfo/...
97,Black Slip-on shoes,https://www.woodlandworldwide.com/productinfo/...
98,Navy Sneaker for Men,https://www.woodlandworldwide.com/productinfo/...
99,BLACK casual sneakers,https://www.woodlandworldwide.com/productinfo/...

In [45]:
woodland_Shoe_men.to_csv('woodland_Shoe_men.csv')

In [3]:
woodland_Shoe_men=pd.read_csv('woodland_Shoe_men.csv')

In [4]:
opening_url = woodland_Shoe_men['opening_url']

In [75]:
woodland_Shoe_Name = woodland_Shoe_men['woodland_Shoe_Name']

.

In [87]:
woodland_Shoe_colour = []

woodland_Shoe_Size1 = []
woodland_Shoe_Size2 = []
woodland_Shoe_Size3 = []
woodland_Shoe_Size4 = []
woodland_Shoe_Size5 = []
woodland_Shoe_Size6 = []
woodland_Shoe_Size7 = []
woodland_Shoe_Size8 = []
woodland_Shoe_Size9 = []
woodland_Shoe_Size10 = []
woodland_Shoe_Size11 = []

woodland_Shoe_original_price = []
woodland_Shoe_discounted_price = []

In [88]:
for p in opening_url:
    driver.get(p)
    time.sleep(5)
    
    
  
    try:
        price= driver.find_element(By.XPATH,'//div[@class="productprice_productprice__IuYyr"]/span[2]')
        woodland_Shoe_original_price.append(price.text)
    except NoSuchElementException:
        woodland_Shoe_original_price.append('_')
        
        
    try:
        pric= driver.find_element(By.XPATH,'//div[@class="productprice_productprice__IuYyr"]/span[1]')
        woodland_Shoe_discounted_price.append(pric.text)
    except NoSuchElementException:
        woodland_Shoe_discounted_price.append('_')
        
        
    try:
        colour= driver.find_element(By.XPATH,'//h5[@class="colorpicker_colorname__sRdk8"]')
        woodland_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        woodland_Shoe_colour.append('_')
        
    try:
        size1= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[1]')
        woodland_Shoe_Size1.append(size1.text)
    except NoSuchElementException:
        woodland_Shoe_Size1.append('_')

    try:
        size2= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[2]')
        woodland_Shoe_Size2.append(size2.text)
    except NoSuchElementException:
        woodland_Shoe_Size2.append('_')
        
    try:
        size3= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[3]')
        woodland_Shoe_Size3.append(size3.text)
    except NoSuchElementException:
        woodland_Shoe_Size3.append('_')
        
    try:
        size4= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[4]')
        woodland_Shoe_Size4.append(size4.text)
    except NoSuchElementException:
        woodland_Shoe_Size4.append('_')
        
    try:
        size5= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[5]')
        woodland_Shoe_Size5.append(size5.text)
    except NoSuchElementException:
        woodland_Shoe_Size5.append('_')
        
    try:
        size6= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[6]')
        woodland_Shoe_Size6.append(size6.text)
    except NoSuchElementException:
        woodland_Shoe_Size6.append('_')
        
    try:
        size7= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[7]')
        woodland_Shoe_Size7.append(size7.text)
    except NoSuchElementException:
        woodland_Shoe_Size7.append('_')
        
    try:
        size8= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[8]')
        woodland_Shoe_Size8.append(size8.text)
    except NoSuchElementException:
        woodland_Shoe_Size8.append('_')
        
    try:
        size9= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[9]')
        woodland_Shoe_Size9.append(size9.text)
    except NoSuchElementException:
        woodland_Shoe_Size9.append('_')
        
    try:
        size10= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[10]')
        woodland_Shoe_Size10.append(size10.text)
    except NoSuchElementException:
        woodland_Shoe_Size10.append('_')
        
    try:
        size11= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[11]')
        woodland_Shoe_Size11.append(size11.text)
    except NoSuchElementException:
        woodland_Shoe_Size11.append('_')

.

In [94]:
woodland_Shoe_men_sportswear1 = pd.DataFrame({'woodland_Shoe_Name':woodland_Shoe_Name,'woodland_Shoe_original_price':woodland_Shoe_original_price,'woodland_Shoe_discounted_price':woodland_Shoe_discounted_price,
                                             'woodland_Shoe_Size1':woodland_Shoe_Size1,'woodland_Shoe_Size2':woodland_Shoe_Size2,'woodland_Shoe_Size3':woodland_Shoe_Size3,'woodland_Shoe_Size4':woodland_Shoe_Size4,'woodland_Shoe_Size5':woodland_Shoe_Size5,
                                             'woodland_Shoe_Size6':woodland_Shoe_Size6,'woodland_Shoe_Size7':woodland_Shoe_Size7,'woodland_Shoe_Size8':woodland_Shoe_Size8,'woodland_Shoe_Size9':woodland_Shoe_Size9,'woodland_Shoe_Size10':woodland_Shoe_Size10,
                                             'woodland_Shoe_Size11':woodland_Shoe_Size11,
                                             'opening_url':opening_url})

In [95]:
woodland_Shoe_men_sportswear1['gender'] = 'men'

In [96]:
woodland_Shoe_men_sportswear1

,woodland_Shoe_Name,woodland_Shoe_original_price,woodland_Shoe_discounted_price,woodland_Shoe_Size1,woodland_Shoe_Size2,woodland_Shoe_Size3,woodland_Shoe_Size4,woodland_Shoe_Size5,woodland_Shoe_Size6,woodland_Shoe_Size7,woodland_Shoe_Size8,woodland_Shoe_Size9,woodland_Shoe_Size10,woodland_Shoe_Size11,opening_url,gender
0,Black Fabric Luxury Sports Shoes,MRP ₹7 495,₹4 497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men
1,Blue sneakers for men,MRP ₹6 495,₹3 897,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men
2,White Fabric Luxury Sports Shoes,MRP ₹7 495,₹4 497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men
3,Beige Fabric Luxury Sports Shoes,MRP ₹7 495,₹4 497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men
4,Black Slip-on Sneaker,MRP ₹5 995,₹3 597,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Grey sneakers for men,MRP ₹7 995,₹3 997,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\n1 Left,45\n3 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men
96,Olive/black sneakers for men,MRP ₹3 795,₹2 277,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\nSold out,45\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men
97,Black Slip-on shoes,MRP ₹2 795,₹2 096,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\nSold out,45\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men
98,Navy Sneaker for Men,MRP ₹2 695,₹2 021,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\nSold out,45\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men
99,BLACK casual sneakers,MRP ₹7 495,₹3 747,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\n1 Left,45\n3 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men

In [97]:
woodland_Shoe_men_sportswear1.to_csv('woodland_Shoe_men_sportswear1.csv')

In [6]:
woodland_Shoe_men_sportswear1=pd.read_csv('woodland_Shoe_men_sportswear1.csv')

In [7]:
opening_url = woodland_Shoe_men_sportswear1['opening_url']

In [14]:
woodland_Shoe_colour = []

In [15]:
for p in opening_url:
    driver.get(p)
    time.sleep(5)
    
    try:
        colour= driver.find_element(By.XPATH,'//h5[@class="colorpicker_colorname__sRdk8"]')
        woodland_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        woodland_Shoe_colour.append('_')

In [18]:
woodland_Shoe_men_sportswear1['woodland_Shoe_colour'] = woodland_Shoe_colour

In [ ]:
woodland_Shoe_men_sportswear1=woodland_Shoe_men_sportswear1.drop('Unnamed: 0',axis=1)

In [23]:
woodland_Shoe_men_sportswear1.to_csv('woodland_Shoe_men_sportswear2.csv')

In [34]:
woodland_Shoe_men_sportswear2 = pd.read_csv('woodland_Shoe_men_sportswear2.csv')
woodland_Shoe_men_sportswear2['type'] = 'sportswear'
woodland_Shoe_men_sportswear2

,Unnamed: 0,woodland_Shoe_Name,woodland_Shoe_original_price,woodland_Shoe_discounted_price,woodland_Shoe_Size1,woodland_Shoe_Size2,woodland_Shoe_Size3,woodland_Shoe_Size4,woodland_Shoe_Size5,woodland_Shoe_Size6,woodland_Shoe_Size7,woodland_Shoe_Size8,woodland_Shoe_Size9,woodland_Shoe_Size10,woodland_Shoe_Size11,opening_url,gender,woodland_Shoe_colour,type
0,0,Black Fabric Luxury Sports Shoes,MRP ₹7 495,₹4 497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLACK,sportswear
1,1,Blue sneakers for men,MRP ₹6 495,₹3 897,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLUE,sportswear
2,2,White Fabric Luxury Sports Shoes,MRP ₹7 495,₹4 497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,WHITE,sportswear
3,3,Beige Fabric Luxury Sports Shoes,MRP ₹7 495,₹4 497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BEIGE,sportswear
4,4,Black Slip-on Sneaker,MRP ₹5 995,₹3 597,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLACK,sportswear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,Grey sneakers for men,MRP ₹7 995,₹3 997,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\n1 Left,45\n3 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,GREY,sportswear
96,96,Olive/black sneakers for men,MRP ₹3 795,₹2 277,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\nSold out,45\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,OLIVE/BLACK,sportswear
97,97,Black Slip-on shoes,MRP ₹2 795,₹2 096,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\nSold out,45\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLACK,sportswear
98,98,Navy Sneaker for Men,MRP ₹2 695,₹2 021,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\nSold out,45\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,NAVY,sportswear
99,99,BLACK casual sneakers,MRP ₹7 495,₹3 747,39\nSold out,40\nSold out,41\nSold out,42\nSold out,43\nSold out,44\n1 Left,45\n3 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLACK,sportswear

In [33]:
driver.close()

.

.

In [16]:
driver = webdriver.Chrome()
driver.get("https://www.woodlandworldwide.com")
time.sleep(5)

In [18]:
search = driver.find_element(By.XPATH,'//a[@class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-umnham"][3]')
search.click()

In [5]:
woodland_Shoe_Name = []
opening_url = []

In [6]:
i = 0
while(i<150):
    driver.execute_script("window.scrollBy(0,200)")
    i+=1
    time.sleep(3)
    

try:
    Name= driver.find_elements(By.XPATH,'//p[@class="productcardplp_productname__F8lks"]')[:150]
    for na in Name:
        woodland_Shoe_Name.append(na.text)
except NoSuchElementException:
    woodland_Shoe_Name.append('_')
    

   
url = driver.find_elements(By.XPATH,'//a[@class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-15kjgm"]')[:150]
for i in url:
    opening_url.append(i.get_attribute('href'))

In [7]:
woodland_Causal_Shoe_men = pd.DataFrame({'woodland_Shoe_Name':woodland_Shoe_Name[:150],'opening_url':opening_url[:150]})
woodland_Causal_Shoe_men

,woodland_Shoe_Name,opening_url
0,Dnavy casual shoes for men,https://www.woodlandworldwide.com/productinfo/...
1,Dnavy 4 casual shoe for men,https://www.woodlandworldwide.com/productinfo/...
2,RB brown Casual shoes for men,https://www.woodlandworldwide.com/productinfo/...
3,Dubai Khaki casual shoes for men,https://www.woodlandworldwide.com/productinfo/...
4,DNAVY shoe for men,https://www.woodlandworldwide.com/productinfo/...
...,...,...
145,Olive green boat shoe for men,https://www.woodlandworldwide.com/productinfo/...
146,Woodland CAMEL casual shoes,https://www.woodlandworldwide.com/productinfo/...
147,Woodland SNAYPE casual sneakers,https://www.woodlandworldwide.com/productinfo/...
148,Dubai Khaki slip-on shoe for men,https://www.woodlandworldwide.com/productinfo/...
149,Woodland Black Casual Shoes,https://www.woodlandworldwide.com/productinfo/...

In [19]:
woodland_Shoe_colour = []

woodland_Shoe_Size1 = []
woodland_Shoe_Size2 = []
woodland_Shoe_Size3 = []
woodland_Shoe_Size4 = []
woodland_Shoe_Size5 = []
woodland_Shoe_Size6 = []
woodland_Shoe_Size7 = []
woodland_Shoe_Size8 = []
woodland_Shoe_Size9 = []
woodland_Shoe_Size10 = []
woodland_Shoe_Size11 = []

woodland_Shoe_original_price = []
woodland_Shoe_discounted_price = []

In [20]:
for p in opening_url:
    driver.get(p)
    time.sleep(5)
    
    
  
    try:
        price= driver.find_element(By.XPATH,'//div[@class="productprice_productprice__IuYyr"]/span[2]')
        woodland_Shoe_original_price.append(price.text)
    except NoSuchElementException:
        woodland_Shoe_original_price.append('_')
        
        
    try:
        pric= driver.find_element(By.XPATH,'//div[@class="productprice_productprice__IuYyr"]/span[1]')
        woodland_Shoe_discounted_price.append(pric.text)
    except NoSuchElementException:
        woodland_Shoe_discounted_price.append('_')
        
        
    try:
        colour= driver.find_element(By.XPATH,'//h5[@class="colorpicker_colorname__sRdk8"]')
        woodland_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        woodland_Shoe_colour.append('_')
        
    try:
        size1= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[1]')
        woodland_Shoe_Size1.append(size1.text)
    except NoSuchElementException:
        woodland_Shoe_Size1.append('_')

    try:
        size2= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[2]')
        woodland_Shoe_Size2.append(size2.text)
    except NoSuchElementException:
        woodland_Shoe_Size2.append('_')
        
    try:
        size3= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[3]')
        woodland_Shoe_Size3.append(size3.text)
    except NoSuchElementException:
        woodland_Shoe_Size3.append('_')
        
    try:
        size4= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[4]')
        woodland_Shoe_Size4.append(size4.text)
    except NoSuchElementException:
        woodland_Shoe_Size4.append('_')
        
    try:
        size5= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[5]')
        woodland_Shoe_Size5.append(size5.text)
    except NoSuchElementException:
        woodland_Shoe_Size5.append('_')
        
    try:
        size6= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[6]')
        woodland_Shoe_Size6.append(size6.text)
    except NoSuchElementException:
        woodland_Shoe_Size6.append('_')
        
    try:
        size7= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[7]')
        woodland_Shoe_Size7.append(size7.text)
    except NoSuchElementException:
        woodland_Shoe_Size7.append('_')
        
    try:
        size8= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[8]')
        woodland_Shoe_Size8.append(size8.text)
    except NoSuchElementException:
        woodland_Shoe_Size8.append('_')
        
    try:
        size9= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[9]')
        woodland_Shoe_Size9.append(size9.text)
    except NoSuchElementException:
        woodland_Shoe_Size9.append('_')
        
    try:
        size10= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[10]')
        woodland_Shoe_Size10.append(size10.text)
    except NoSuchElementException:
        woodland_Shoe_Size10.append('_')
        
    try:
        size11= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[11]')
        woodland_Shoe_Size11.append(size11.text)
    except NoSuchElementException:
        woodland_Shoe_Size11.append('_')

In [25]:
woodland_Shoe_men_Causal = pd.DataFrame({'woodland_Shoe_Name':woodland_Shoe_Name,'woodland_Shoe_original_price':woodland_Shoe_original_price,'woodland_Shoe_discounted_price':woodland_Shoe_discounted_price,'woodland_Shoe_colour':woodland_Shoe_colour,
                                             'woodland_Shoe_Size1':woodland_Shoe_Size1,'woodland_Shoe_Size2':woodland_Shoe_Size2,'woodland_Shoe_Size3':woodland_Shoe_Size3,'woodland_Shoe_Size4':woodland_Shoe_Size4,'woodland_Shoe_Size5':woodland_Shoe_Size5,
                                             'woodland_Shoe_Size6':woodland_Shoe_Size6,'woodland_Shoe_Size7':woodland_Shoe_Size7,'woodland_Shoe_Size8':woodland_Shoe_Size8,'woodland_Shoe_Size9':woodland_Shoe_Size9,'woodland_Shoe_Size10':woodland_Shoe_Size10,
                                             'woodland_Shoe_Size11':woodland_Shoe_Size11,
                                             'opening_url':opening_url})

In [92]:
woodland_Shoe_men_Causal['gender'] = 'men'
woodland_Shoe_men_Causal['type'] = 'casual'

In [27]:
woodland_Shoe_men_Causal.to_csv('woodland_Shoe_men_Causal.csv')

In [37]:
woodland_Shoe_men_Causal = pd.read_csv('woodland_Shoe_men_Causal.csv')

In [ ]:
driver.close()

.

.

.

# WOMEN

In [29]:
driver = webdriver.Chrome()
driver.get("https://www.woodlandworldwide.com/product-list/WOMEN_SNEAKERS")
time.sleep(5)

In [39]:
search = driver.find_element(By.XPATH,'//button[@class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-vhrx17"][2]')
search.click()

In [40]:
search2 = driver.find_element(By.XPATH,'/html/body/div[1]/header/div[5]/div/div/div/div[2]/div[1]/h5[2]')
search2.click()

In [41]:
woodland_Shoe_Name = []
opening_url = []

In [ ]:
i = 0
while(i<50):
    driver.execute_script("window.scrollBy(0,100)")
    i+=1
    time.sleep(3)

In [42]:

    

try:
    Name= driver.find_elements(By.XPATH,'//p[@class="productcardplp_productname__F8lks"]')[:70]
    for na in Name:
        woodland_Shoe_Name.append(na.text)
except NoSuchElementException:
    woodland_Shoe_Name.append('_')
    

   
url = driver.find_elements(By.XPATH,'//a[@class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-15kjgm"]')[:70]
for i in url:
    opening_url.append(i.get_attribute('href'))

In [43]:
woodland_Shoe_women_sportswear = pd.DataFrame({'woodland_Shoe_Name':woodland_Shoe_Name[:150],'opening_url':opening_url[:150]})
woodland_Shoe_women_sportswear

,woodland_Shoe_Name,opening_url
0,Brown/maroon Canvas shoes for women,https://www.woodlandworldwide.com/productinfo/...
1,Lgrey sneaker for women,https://www.woodlandworldwide.com/productinfo/...
2,Variglia Sneakers for Women,https://www.woodlandworldwide.com/productinfo/...
3,Woodland DCadet Blue casual sneakers,https://www.woodlandworldwide.com/productinfo/...
4,DBLUE casual sneakers,https://www.woodlandworldwide.com/productinfo/...
...,...,...
65,Woods Red chunky sole sneakers,https://www.woodlandworldwide.com/productinfo/...
66,White casual sneakers for women,https://www.woodlandworldwide.com/productinfo/...
67,White high-top sneaker for women,https://www.woodlandworldwide.com/productinfo/...
68,Woods DSKY BLUE rose casual sneakers for women,https://www.woodlandworldwide.com/productinfo/...
69,Woods WHITE casual sneakers,https://www.woodlandworldwide.com/productinfo/...

In [44]:
woodland_Shoe_colour = []

woodland_Shoe_Size1 = []
woodland_Shoe_Size2 = []
woodland_Shoe_Size3 = []
woodland_Shoe_Size4 = []
woodland_Shoe_Size5 = []
woodland_Shoe_Size6 = []
woodland_Shoe_Size7 = []
woodland_Shoe_Size8 = []
woodland_Shoe_Size9 = []
woodland_Shoe_Size10 = []
woodland_Shoe_Size11 = []

woodland_Shoe_original_price = []
woodland_Shoe_discounted_price = []

In [45]:
for p in opening_url:
    driver.get(p)
    time.sleep(5)
    
    
  
    try:
        price= driver.find_element(By.XPATH,'//div[@class="productprice_productprice__IuYyr"]/span[2]')
        woodland_Shoe_original_price.append(price.text)
    except NoSuchElementException:
        woodland_Shoe_original_price.append('_')
        
        
    try:
        pric= driver.find_element(By.XPATH,'//div[@class="productprice_productprice__IuYyr"]/span[1]')
        woodland_Shoe_discounted_price.append(pric.text)
    except NoSuchElementException:
        woodland_Shoe_discounted_price.append('_')
        
        
    try:
        colour= driver.find_element(By.XPATH,'//h5[@class="colorpicker_colorname__sRdk8"]')
        woodland_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        woodland_Shoe_colour.append('_')
        
    try:
        size1= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[1]')
        woodland_Shoe_Size1.append(size1.text)
    except NoSuchElementException:
        woodland_Shoe_Size1.append('_')

    try:
        size2= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[2]')
        woodland_Shoe_Size2.append(size2.text)
    except NoSuchElementException:
        woodland_Shoe_Size2.append('_')
        
    try:
        size3= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[3]')
        woodland_Shoe_Size3.append(size3.text)
    except NoSuchElementException:
        woodland_Shoe_Size3.append('_')
        
    try:
        size4= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[4]')
        woodland_Shoe_Size4.append(size4.text)
    except NoSuchElementException:
        woodland_Shoe_Size4.append('_')
        
    try:
        size5= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[5]')
        woodland_Shoe_Size5.append(size5.text)
    except NoSuchElementException:
        woodland_Shoe_Size5.append('_')
        
    try:
        size6= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[6]')
        woodland_Shoe_Size6.append(size6.text)
    except NoSuchElementException:
        woodland_Shoe_Size6.append('_')
        
    try:
        size7= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[7]')
        woodland_Shoe_Size7.append(size7.text)
    except NoSuchElementException:
        woodland_Shoe_Size7.append('_')
        
    try:
        size8= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[8]')
        woodland_Shoe_Size8.append(size8.text)
    except NoSuchElementException:
        woodland_Shoe_Size8.append('_')
        
    try:
        size9= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[9]')
        woodland_Shoe_Size9.append(size9.text)
    except NoSuchElementException:
        woodland_Shoe_Size9.append('_')
        
    try:
        size10= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[10]')
        woodland_Shoe_Size10.append(size10.text)
    except NoSuchElementException:
        woodland_Shoe_Size10.append('_')
        
    try:
        size11= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[11]')
        woodland_Shoe_Size11.append(size11.text)
    except NoSuchElementException:
        woodland_Shoe_Size11.append('_')

In [47]:
woodland_Shoe_women_sportswear = pd.DataFrame({'woodland_Shoe_Name':woodland_Shoe_Name,'woodland_Shoe_original_price':woodland_Shoe_original_price,'woodland_Shoe_discounted_price':woodland_Shoe_discounted_price,'woodland_Shoe_colour':woodland_Shoe_colour,
                                             'woodland_Shoe_Size1':woodland_Shoe_Size1,'woodland_Shoe_Size2':woodland_Shoe_Size2,'woodland_Shoe_Size3':woodland_Shoe_Size3,'woodland_Shoe_Size4':woodland_Shoe_Size4,'woodland_Shoe_Size5':woodland_Shoe_Size5,
                                             'woodland_Shoe_Size6':woodland_Shoe_Size6,'woodland_Shoe_Size7':woodland_Shoe_Size7,'woodland_Shoe_Size8':woodland_Shoe_Size8,'woodland_Shoe_Size9':woodland_Shoe_Size9,'woodland_Shoe_Size10':woodland_Shoe_Size10,
                                             'woodland_Shoe_Size11':woodland_Shoe_Size11,
                                             'opening_url':opening_url})

In [90]:
woodland_Shoe_women_sportswear['gender'] = 'women'
woodland_Shoe_women_sportswear['type'] = 'sportswear'
woodland_Shoe_women_sportswear

,Unnamed: 0,woodland_Shoe_Name,woodland_Shoe_original_price,woodland_Shoe_discounted_price,woodland_Shoe_colour,woodland_Shoe_Size1,woodland_Shoe_Size2,woodland_Shoe_Size3,woodland_Shoe_Size4,woodland_Shoe_Size5,woodland_Shoe_Size6,woodland_Shoe_Size7,woodland_Shoe_Size8,woodland_Shoe_Size9,woodland_Shoe_Size10,woodland_Shoe_Size11,opening_url,gender,type
0,0,Brown/maroon Canvas shoes for women,MRP ₹4 495,₹2 247,BROWN/MAROON,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear
1,1,Lgrey sneaker for women,_,₹4 995,LGREY,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear
2,2,Variglia Sneakers for Women,_,₹4 495,VARIGLIA,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear
3,3,Woodland DCadet Blue casual sneakers,_,₹4 995,DCADET BLUE,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear
4,4,DBLUE casual sneakers,MRP ₹4 995,₹2 497,DBLUE,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,65,Woods Red chunky sole sneakers,MRP ₹5 995,₹2 000,RED,35\nSold out,36\nSold out,37\nSold out,38,39\n2 Left,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear
66,66,White casual sneakers for women,MRP ₹5 495,₹2 747,WHITE,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\n1 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear
67,67,White high-top sneaker for women,MRP ₹4 495,₹1 500,WHITE,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear
68,68,Woods DSKY BLUE rose casual sneakers for women,MRP ₹4 695,₹2 817,DSKY BLUE,35\nSold out,36\nSold out,37\n2 Left,38\nSold out,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear
69,69,Woods WHITE casual sneakers,MRP ₹8 995,₹5 397,WHITE,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\n2 Left,41\n2 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,sportswear

In [91]:
woodland_Shoe_women_sportswear.to_csv('woodland_Shoe_women_sportswear.csv')

In [89]:
woodland_Shoe_women_sportswear = pd.read_csv('woodland_Shoe_women_sportswear.csv')

In [ ]:
driver.close()

.

.

In [6]:
driver = webdriver.Chrome()
driver.get("https://www.woodlandworldwide.com")
time.sleep(5)

In [22]:
search1 = driver.find_element(By.XPATH,'//button[@class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-vhrx17"][2]')
search1.click()

In [23]:
search2 = driver.find_element(By.XPATH,'/html/body/div[1]/header/div[5]/div/div/div/div[2]/div[1]/div/h5[3]')
search2.click()

In [13]:
woodland_Shoe_Name = []
opening_url = []

In [14]:
i = 0
while(i<50):
    driver.execute_script("window.scrollBy(0,50)")
    i+=1
    time.sleep(3)
    

try:
    Name= driver.find_elements(By.XPATH,'//p[@class="productcardplp_productname__F8lks"]')[:150]
    for na in Name:
        woodland_Shoe_Name.append(na.text)
except NoSuchElementException:
    woodland_Shoe_Name.append('_')
    

   
url = driver.find_elements(By.XPATH,'//a[@class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-15kjgm"]')[:150]
for i in url:
    opening_url.append(i.get_attribute('href'))

In [16]:
len(woodland_Shoe_Name)

53

In [26]:
woodland_Shoe_colour = []

woodland_Shoe_Size1 = []
woodland_Shoe_Size2 = []
woodland_Shoe_Size3 = []
woodland_Shoe_Size4 = []
woodland_Shoe_Size5 = []
woodland_Shoe_Size6 = []
woodland_Shoe_Size7 = []
woodland_Shoe_Size8 = []
woodland_Shoe_Size9 = []
woodland_Shoe_Size10 = []
woodland_Shoe_Size11 = []

woodland_Shoe_original_price = []
woodland_Shoe_discounted_price = []

In [28]:
for p in opening_url:
    driver.get(p)
    time.sleep(5)
    
    
  
    try:
        price= driver.find_element(By.XPATH,'//span[@class="productprice_mrpprice__7zMlK" or@class="productprice_offerprice__RLPOw"]')
        woodland_Shoe_original_price.append(price.text)
    except NoSuchElementException:
        woodland_Shoe_original_price.append('_')
        
        
    try:
        pric= driver.find_element(By.XPATH,'//div[@class="productprice_productprice__IuYyr"]/span[1]')
        woodland_Shoe_discounted_price.append(pric.text)
    except NoSuchElementException:
        woodland_Shoe_discounted_price.append('_')
        
        
    try:
        colour= driver.find_element(By.XPATH,'//h5[@class="colorpicker_colorname__sRdk8"]')
        woodland_Shoe_colour.append(colour.text)
    except NoSuchElementException:
        woodland_Shoe_colour.append('_')
        
    try:
        size1= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[1]')
        woodland_Shoe_Size1.append(size1.text)
    except NoSuchElementException:
        woodland_Shoe_Size1.append('_')

    try:
        size2= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[2]')
        woodland_Shoe_Size2.append(size2.text)
    except NoSuchElementException:
        woodland_Shoe_Size2.append('_')
        
    try:
        size3= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[3]')
        woodland_Shoe_Size3.append(size3.text)
    except NoSuchElementException:
        woodland_Shoe_Size3.append('_')
        
    try:
        size4= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[4]')
        woodland_Shoe_Size4.append(size4.text)
    except NoSuchElementException:
        woodland_Shoe_Size4.append('_')
        
    try:
        size5= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[5]')
        woodland_Shoe_Size5.append(size5.text)
    except NoSuchElementException:
        woodland_Shoe_Size5.append('_')
        
    try:
        size6= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[6]')
        woodland_Shoe_Size6.append(size6.text)
    except NoSuchElementException:
        woodland_Shoe_Size6.append('_')
        
    try:
        size7= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[7]')
        woodland_Shoe_Size7.append(size7.text)
    except NoSuchElementException:
        woodland_Shoe_Size7.append('_')
        
    try:
        size8= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[8]')
        woodland_Shoe_Size8.append(size8.text)
    except NoSuchElementException:
        woodland_Shoe_Size8.append('_')
        
    try:
        size9= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[9]')
        woodland_Shoe_Size9.append(size9.text)
    except NoSuchElementException:
        woodland_Shoe_Size9.append('_')
        
    try:
        size10= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[10]')
        woodland_Shoe_Size10.append(size10.text)
    except NoSuchElementException:
        woodland_Shoe_Size10.append('_')
        
    try:
        size11= driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]/div/div[11]')
        woodland_Shoe_Size11.append(size11.text)
    except NoSuchElementException:
        woodland_Shoe_Size11.append('_')

KeyboardInterrupt

In [30]:
woodland_Shoe_women_loafers = pd.DataFrame({'woodland_Shoe_Name':woodland_Shoe_Name[:50],'woodland_Shoe_original_price':woodland_Shoe_original_price[:50],'woodland_Shoe_discounted_price':woodland_Shoe_discounted_price[:50],'woodland_Shoe_colour':woodland_Shoe_colour[:50],
                                             'woodland_Shoe_Size1':woodland_Shoe_Size1[:50],'woodland_Shoe_Size2':woodland_Shoe_Size2[:50],'woodland_Shoe_Size3':woodland_Shoe_Size3[:50],'woodland_Shoe_Size4':woodland_Shoe_Size4[:50],'woodland_Shoe_Size5':woodland_Shoe_Size5[:50],
                                             'woodland_Shoe_Size6':woodland_Shoe_Size6[:50],'woodland_Shoe_Size7':woodland_Shoe_Size7[:50],'woodland_Shoe_Size8':woodland_Shoe_Size8[:50],'woodland_Shoe_Size9':woodland_Shoe_Size9[:50],'woodland_Shoe_Size10':woodland_Shoe_Size10[:50],
                                             'woodland_Shoe_Size11':woodland_Shoe_Size11[:50],
                                             'opening_url':opening_url[:50]})

In [31]:
woodland_Shoe_women_loafers['gender'] = 'women'
woodland_Shoe_women_loafers['type'] = 'loafers'
woodland_Shoe_women_loafers

,woodland_Shoe_Name,woodland_Shoe_original_price,woodland_Shoe_discounted_price,woodland_Shoe_colour,woodland_Shoe_Size1,woodland_Shoe_Size2,woodland_Shoe_Size3,woodland_Shoe_Size4,woodland_Shoe_Size5,woodland_Shoe_Size6,woodland_Shoe_Size7,woodland_Shoe_Size8,woodland_Shoe_Size9,woodland_Shoe_Size10,woodland_Shoe_Size11,opening_url,gender,type
0,Black slip-on shoes,₹1 995,₹1 995,BLACK,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
1,Woodland Wine Hoodie for women,₹2 697,₹2 697,WINE,XS\nSold out,S,M,L,XL,2X,_,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
2,Cream loafer for women,₹5 059,₹5 059,CREAM,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
3,Beige Shoes for women,₹2 427,₹2 427,BEIGE,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
4,Yellow Wedge Heel Loafer for Women,₹6 995,₹6 995,YELLOW,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
5,Brown Loafer for Women,₹6 995,₹6 995,BROWN,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
6,Grey leather mule,₹3 777,₹3 777,GREY,35\nSold out,36\n4 Left,37,38,39,40,41\n2 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
7,Woodland CAMEL loafers for women,₹1 077,₹1 077,CAMEL,35\nSold out,36\nSold out,37\n3 Left,38\nSold out,39\n3 Left,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
8,Beige loafer for women,₹2 697,₹2 697,BEIGE,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\n4 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
9,Black Penny Loafer for Women,₹6 995,₹6 995,BLACK,35\nSold out,36,37,38,39,40,41\n3 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
10,Red Wedge Heel Loafer for Women,₹6 995,₹6 995,RED,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
11,Woodland LGREY 2 loafers for women,₹1 131,₹1 131,LGREY 2,35\nSold out,36\nSold out,37\n1 Left,38\nSold out,39\n2 Left,40,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
12,Black Loafer for Women,₹6 995,₹6 995,BLACK,35\nSold out,36,37,38,39,40,41\n3 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
13,Black Loafer for Women,₹6 995,₹6 995,BLACK,35\nSold out,36,37,38,39,40,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
14,White Loafer for Women,₹6 995,₹6 995,WHITE,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
15,Pink wedge loafers for women,₹2 697,₹2 697,PINK,35\nSold out,36\nSold out,37\n2 Left,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
16,Beige Loafer for Women,₹6 995,₹6 995,BEIGE,35\nSold out,36,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
17,White loafers for women,₹2 697,₹2 697,WHITE,35\nSold out,36\n4 Left,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
18,Woodland lbeige moccasins for women,₹2 022,₹2 022,LBEIGE,35\nSold out,36\n1 Left,37\n1 Left,38,39,40\n3 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
19,Blue Wedge Heel for women,₹4 857,₹4 857,BLUE,35\nSold out,36\nSold out,37\n3 Left,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
20,White Penny Loafer for Women,₹6 995,₹6 995,WHITE,35\nSold out,36,37,38,39,40\nSold out,41\n1 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
21,camel loafers for women,₹900,₹900,CAMEL,35,36\n3 Left,37\nSold out,38\nSold out,39\nSold out,40\n3 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
22,Black loafer for women,₹2 697,₹2 697,BLACK,35\nSold out,36\nSold out,37\n2 Left,38\n3 Left,39,40,41\n1 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
23,Black casual loafer for women,₹2 697,₹2 697,BLACK,35\nSold out,36\nSold out,37,38,39,40,41\n2 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
24,Woods Grey slip-on shoes,₹4 587,₹4 587,GREY,35\nSold out,36\n1 Left,37,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
25,LTAN moccasins for women,₹1 797,₹1 797,LTAN,35\nSold out,36,37,38,39,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
26,BROWN loafers for women,₹3 237,₹3 237,BROWN,35\nSold out,36\nSold out,37\n3 Left,38\n4 Left,39,40,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
27,Scarlet Red Loafers for women,₹3 507,₹3 507,CLARET RED,35\nSold out,36\n3 Left,37\nSold out,38,39,40,41,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
28,CAMEL moccasin for women,₹897,₹897,CAMEL,35\n4 Left,36,37\n1 Left,38\n1 Left,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
29,PINK moccasins for women,₹4 317,₹4 317,PINK,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\n1 Left,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
30,Black leather loafer for women,₹3 237,₹3 237,BLACK,35\nSold out,36\nSold out,37,38\n2 Left,39,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
31,Woods Black loafers for women,_,_,_,_,_,_,_,_,_,_,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
32,Woods BLACK slip-on shoes,₹4 587,₹4 587,BLACK,35\nSold out,36\n4 Left,37\n1 Left,38,39\n3 Left,40,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
33,Beige Wedge Heel for women,₹4 857,₹4 857,BEIGE,35\nSold out,36\nSold out,37\nSold out,38,39,40,41\n2 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
34,BORDO moccasins for women,₹2 157,₹2 157,BORDO,35\nSold out,36,37\n4 Left,38\nSold out,39\nSold out,40\n1 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
35,Black loafers for women,₹897,₹897,BLACK,35\n2 Left,36\n2 Left,37,38\nSold out,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
36,Beige loafer for women,₹4 317,₹4 317,BEIGE,35\nSold out,36\n4 Left,37\n3 Left,38\n2 Left,39,40\n1 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
37,Red leather loafer for women,₹3 237,₹3 237,RED,35\nSold out,36\n1 Left,37,38\nSold out,39\n4 Left,40\n1 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
38,Black slip-on shoe for women,₹3 507,₹3 507,BLACK,35\nSold out,36\nSold out,37\nSold out,38,39\n1 Left,40\n4 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
39,Black loafer for women,₹1 350,₹1 350,BLACK,35\nSold out,36\nSold out,37\nSold out,38\n1 Left,39\n3 Left,40,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
40,Khaki casual sneakers for women,₹1 800,₹1 800,KHAKI,35\nSold out,36\nSold out,37\nSold out,38\n2 Left,39\n4 Left,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
41,Woods BLACK Slip-on shoes for women,₹2 967,₹2 967,BLACK,35\nSold out,36\nSold out,37\n1 Left,38\nSold out,39\nSold out,40\n4 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
42,RED loafers for women,₹3 183,₹3 183,RED,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\n2 Left,40\n4 Left,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
43,Woods BLACK wedge heel,₹4 047,₹4 047,BLACK,35\nSold out,36\nSold out,37\nSold out,38\n1 Left,39\n4 Left,40,41\n1 Left,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
44,Black slip-onm shoes,₹900,₹900,BLACK,35\n1 Left,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
45,BEIGE moccasins for women,₹1 752,₹1 752,BEIGE,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
46,BRIGHT RBLUE loafers for women,₹1 347,₹1 347,BRIGHT RBLUE,35\n1 Left,36\nSold out,37\n2 Left,38\n2 Left,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
47,KHAKI moccasins for women,₹2 157,₹2 157,KHAKI,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\n3 Left,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
48,Red penny loafer for women,₹900,₹900,RED,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers
49,WHITE loafers for women,₹3 237,₹3 237,WHITE,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,loafers

In [32]:
woodland_Shoe_women_loafers.to_csv('woodland_Shoe_women_loafers.csv')

.

.

.

In [ ]:
#woodland_Shoe_men_sportswear2
#woodland_Shoe_men_Causal
#woodland_Shoe_women_sportswear
#woodland_Shoe_women_loafers

In [93]:
woodland_Shoe = pd.concat([woodland_Shoe_men_sportswear2,woodland_Shoe_men_Causal,woodland_Shoe_women_sportswear,woodland_Shoe_women_loafers],ignore_index=True)
woodland_Shoe = woodland_Shoe.drop('Unnamed: 0',axis=1)

woodland_Shoe

,woodland_Shoe_Name,woodland_Shoe_original_price,woodland_Shoe_discounted_price,woodland_Shoe_Size1,woodland_Shoe_Size2,woodland_Shoe_Size3,woodland_Shoe_Size4,woodland_Shoe_Size5,woodland_Shoe_Size6,woodland_Shoe_Size7,woodland_Shoe_Size8,woodland_Shoe_Size9,woodland_Shoe_Size10,woodland_Shoe_Size11,opening_url,gender,woodland_Shoe_colour,type
0,Black Fabric Luxury Sports Shoes,MRP ₹7 495,₹4 497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLACK,sportswear
1,Blue sneakers for men,MRP ₹6 495,₹3 897,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLUE,sportswear
2,White Fabric Luxury Sports Shoes,MRP ₹7 495,₹4 497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,WHITE,sportswear
3,Beige Fabric Luxury Sports Shoes,MRP ₹7 495,₹4 497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BEIGE,sportswear
4,Black Slip-on Sneaker,MRP ₹5 995,₹3 597,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLACK,sportswear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,BEIGE moccasins for women,₹1 752,₹1 752,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,BEIGE,loafers
366,BRIGHT RBLUE loafers for women,₹1 347,₹1 347,35\n1 Left,36\nSold out,37\n2 Left,38\n2 Left,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,BRIGHT RBLUE,loafers
367,KHAKI moccasins for women,₹2 157,₹2 157,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\n3 Left,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,KHAKI,loafers
368,Red penny loafer for women,₹900,₹900,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,RED,loafers
369,WHITE loafers for women,₹3 237,₹3 237,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,WHITE,loafers

In [94]:
woodland_Shoe['brand'] = 'woodland'

In [95]:
d=woodland_Shoe['woodland_Shoe_original_price'].str.replace(' ','')
a=d.str.extract('(\d+)')
woodland_Shoe['woodland_Shoe_original_price'] = a

In [96]:
xx=woodland_Shoe['woodland_Shoe_discounted_price'].str.replace(' ','')
xy=xx.str.extract('(\d+)')
woodland_Shoe['woodland_Shoe_discounted_price'] = xy

In [97]:
woodland_Shoe

,woodland_Shoe_Name,woodland_Shoe_original_price,woodland_Shoe_discounted_price,woodland_Shoe_Size1,woodland_Shoe_Size2,woodland_Shoe_Size3,woodland_Shoe_Size4,woodland_Shoe_Size5,woodland_Shoe_Size6,woodland_Shoe_Size7,woodland_Shoe_Size8,woodland_Shoe_Size9,woodland_Shoe_Size10,woodland_Shoe_Size11,opening_url,gender,woodland_Shoe_colour,type,brand
0,Black Fabric Luxury Sports Shoes,7495,4497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLACK,sportswear,woodland
1,Blue sneakers for men,6495,3897,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLUE,sportswear,woodland
2,White Fabric Luxury Sports Shoes,7495,4497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,WHITE,sportswear,woodland
3,Beige Fabric Luxury Sports Shoes,7495,4497,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BEIGE,sportswear,woodland
4,Black Slip-on Sneaker,5995,3597,39\nSold out,40,41,42,43,44,45,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,men,BLACK,sportswear,woodland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,BEIGE moccasins for women,1752,1752,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,BEIGE,loafers,woodland
366,BRIGHT RBLUE loafers for women,1347,1347,35\n1 Left,36\nSold out,37\n2 Left,38\n2 Left,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,BRIGHT RBLUE,loafers,woodland
367,KHAKI moccasins for women,2157,2157,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\n3 Left,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,KHAKI,loafers,woodland
368,Red penny loafer for women,900,900,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40\nSold out,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,RED,loafers,woodland
369,WHITE loafers for women,3237,3237,35\nSold out,36\nSold out,37\nSold out,38\nSold out,39\nSold out,40,41\nSold out,_,_,_,_,https://www.woodlandworldwide.com/productinfo/...,women,WHITE,loafers,woodland

In [98]:
woodland_Shoe.to_csv('woodland_Shoe.csv')

In [100]:
# no reviews/ratings or product code avilable on the website

.

.

.

In [45]:
adidas_Shoe=pd.read_csv('adidas_Shoe.csv')
Nike_Shoe=pd.read_csv('Nike_Shoe.csv')
puma_Shoe1=pd.read_csv('puma_Shoe1.csv')
woodland_Shoe=pd.read_csv('woodland_Shoe.csv')

In [46]:
adidas_Shoe=adidas_Shoe.drop('Unnamed: 0',axis=1)
Nike_Shoe=Nike_Shoe.drop('Unnamed: 0',axis=1)
puma_Shoe1=puma_Shoe1.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1)
woodland_Shoe=woodland_Shoe.drop('Unnamed: 0',axis=1)

In [47]:
adidas_Shoe['selling_price'] = adidas_Shoe['adidas_Shoe_discounted_price'].fillna(adidas_Shoe['adidas_Shoe_original_price'])
Nike_Shoe['selling_price'] = Nike_Shoe['Nike_Shoe_price']
puma_Shoe1['selling_price'] = puma_Shoe1['puma_Shoe_discounted_price'].fillna(puma_Shoe1['puma_Shoe_original_price'])
woodland_Shoe['selling_price'] = woodland_Shoe['woodland_Shoe_discounted_price'].fillna(woodland_Shoe['woodland_Shoe_original_price'])

In [48]:
adidas_Shoe['selling_price'].describe()

count      300.000000
mean     13749.716667
std      12301.984269
min       1349.000000
25%       6599.000000
50%      10749.000000
75%      18249.000000
max      69999.000000
Name: selling_price, dtype: float64

In [49]:
def quality1(selling_price):
    if selling_price < 4000:
        return 'average'
    elif selling_price < 10000:
        return 'good'
    elif selling_price < 18999:
        return 'great'
    else:
        return 'best'
    
adidas_Shoe['quality'] = adidas_Shoe['selling_price'].apply(quality1)

In [50]:
Nike_Shoe['selling_price'].describe()

count      300.000000
mean     11558.333333
std       5157.277764
min       1695.000000
25%       7995.000000
50%      10795.000000
75%      14995.000000
max      27995.000000
Name: selling_price, dtype: float64

In [51]:
def quality2(selling_price):
    if selling_price < 5000:
        return 'average'
    elif selling_price < 10000:
        return 'good'
    elif selling_price < 14000:
        return 'great'
    else:
        return 'best'
    
Nike_Shoe['quality'] = Nike_Shoe['selling_price'].apply(quality2)

In [52]:
puma_Shoe1['selling_price'].describe()

count      255.000000
mean      5686.964706
std       5732.253572
min       1411.000000
25%       2905.000000
50%       3486.000000
75%       6557.000000
max      37350.000000
Name: selling_price, dtype: float64

In [53]:
def quality3(selling_price):
    if selling_price < 3000:
        return 'average'
    elif selling_price < 5000:
        return 'good'
    elif selling_price < 10000:
        return 'great'
    else:
        return 'best'
    
puma_Shoe1['quality'] = puma_Shoe1['selling_price'].apply(quality3)

In [54]:
woodland_Shoe['selling_price'].describe()

count      358.000000
mean      3369.162011
std       1912.665978
min        897.000000
25%       2217.000000
50%       2747.000000
75%       4195.000000
max      14995.000000
Name: selling_price, dtype: float64

In [55]:
def quality3(selling_price):
    if selling_price < 2000:
        return 'average'
    elif selling_price < 4000:
        return 'good'
    elif selling_price < 8000:
        return 'great'
    else:
        return 'best'
    
woodland_Shoe['quality'] = woodland_Shoe['selling_price'].apply(quality3)

In [56]:
adidas_Shoe.columns

Index(['adidas_Shoe_Name', 'adidas_Shoe_original_price',
       'adidas_Shoe_discounted_price', 'adidas_Shoe_type',
       'adidas_Shoe_Number_of_colour', 'adidas_opening_url',
       'adidas_Shoe_Reviews', 'adidas_Shoe_Star_Rating',
       'adidas_Shoe_Product_Code', 'brand', 'gender', 'colour1', 'colour2',
       'colour3', 'colour4', 'selling_price', 'quality'],
      dtype='object')

In [57]:
adidas_Shoe.columns=['Name', 'original_price',
       'discounted_price', 'type',
       'Number_of_colour', 'opening_url',
       'Reviews', 'Rating',
       'Product_Code', 'brand', 'gender', 'colour1', 'colour2',
       'colour3', 'colour4', 'selling_price', 'quality']

In [58]:
Nike_Shoe.columns

Index(['Nike_Shoe_Name', 'Nike_Shoe_Number_of_colour', 'Nike_Shoe_price',
       'Nike_Shoe_Size_Count', 'Nike_Shoe_Product_Code', 'Nike_Shoe_Reviews',
       'Nike_Shoe_Star_Rating', 'opening_url', 'Nike_Shoe_Size1',
       'Nike_Shoe_Size2', 'Nike_Shoe_Size3', 'Nike_Shoe_Size4',
       'Nike_Shoe_Size5', 'Nike_Shoe_Size6', 'Nike_Shoe_Size7',
       'Nike_Shoe_Size8', 'Nike_Shoe_Size9', 'Nike_Shoe_Size10',
       'Nike_Shoe_Size11', 'Nike_Shoe_Size12', 'Nike_Shoe_Size13',
       'Nike_Shoe_Size14', 'Nike_Shoe_Size15', 'Nike_Shoe_Size16',
       'Nike_Shoe_Size17', 'Nike_Shoe_Size18', 'Nike_Shoe_Size19',
       'Nike_Shoe_Size20', 'Nike_Shoe_Size21', 'Nike_Shoe_Size22',
       'Nike_Shoe_Size23', 'Nike_Shoe_Size24', 'Nike_Shoe_Size25', 'gender',
       'brand', 'colour1', 'colour2', 'colour3', 'colour4', 'selling_price',
       'quality'],
      dtype='object')

In [59]:
Nike_Shoe.columns=['Name', 'Number_of_colour', 'original_price',
       'Size_Count', 'Product_Code', 'Reviews',
       'Rating', 'opening_url',
       'Size1', 'Size2', 'Size3',
       'Size4', 'Size5', 'Size6',
       'Size7', 'Size8', 'Size9',
       'Size10', 'Size11', 'Size12',
       'Size13', 'Size14', 'Size15',
       'Size16', 'Size17', 'Size18',
       'Size19', 'Size20', 'Size21',
       'Size22', 'Size23', 'Size24',
       'Size25', 'gender', 'brand', 'colour1', 'colour2', 'colour3',
       'colour4','selling_price','quality']

In [60]:
puma_Shoe1.columns

Index(['puma_Shoe_Name', 'puma_Shoe_original_price',
       'puma_Shoe_discounted_price', 'puma_Shoe_Number_of_colour',
       'puma_Shoe_Product_Code', 'puma_Shoe_Reviews', 'puma_Shoe_Star_Rating',
       'puma_Shoe_Size1', 'puma_Shoe_Size2', 'puma_Shoe_Size3',
       'puma_Shoe_Size4', 'puma_Shoe_Size5', 'puma_Shoe_Size6',
       'puma_Shoe_Size7', 'puma_Shoe_Size8', 'puma_Shoe_Size9',
       'puma_Shoe_Size10', 'puma_Shoe_Size11', 'puma_Shoe_Size12',
       'puma_Shoe_Size13', 'puma_Shoe_Size14', 'puma_Shoe_Size15',
       'puma_Shoe_Size16', 'puma_Shoe_Size17', 'puma_Shoe_Size18',
       'puma_Shoe_Size19', 'puma_Shoe_Size20', 'puma_Shoe_Size21',
       'puma_Shoe_Size22', 'puma_Shoe_Size23', 'puma_Shoe_Size24',
       'puma_Shoe_Size25', 'opening_url', 'gender', 'brand', 'colour1',
       'colour2', 'colour3', 'colour4', 'selling_price', 'quality'],
      dtype='object')

In [61]:
puma_Shoe1.columns=['Name', 'original_price',
       'discounted_price', 'Number_of_colour',
       'Product_Code', 'Reviews', 'Rating',
       'Size1', 'Size2', 'Size3',
       'Size4', 'Size5', 'Size6',
       'Size7', 'Size8', 'Size9',
       'Size10', 'Size11', 'Size12',
       'Size13', 'Size14', 'Size15',
       'Size16', 'Size17', 'Size18',
       'Size19', 'Size20', 'Size21',
       'Size22', 'Size23', 'Size24',
       'Size25', 'opening_url', 'gender', 'brand', 'colour1',
       'colour2', 'colour3', 'colour4', 'selling_price', 'quality']

In [62]:
woodland_Shoe.columns

Index(['woodland_Shoe_Name', 'woodland_Shoe_original_price',
       'woodland_Shoe_discounted_price', 'woodland_Shoe_Size1',
       'woodland_Shoe_Size2', 'woodland_Shoe_Size3', 'woodland_Shoe_Size4',
       'woodland_Shoe_Size5', 'woodland_Shoe_Size6', 'woodland_Shoe_Size7',
       'woodland_Shoe_Size8', 'woodland_Shoe_Size9', 'woodland_Shoe_Size10',
       'woodland_Shoe_Size11', 'opening_url', 'gender', 'woodland_Shoe_colour',
       'type', 'brand', 'selling_price', 'quality'],
      dtype='object')

In [63]:
woodland_Shoe.columns=['Name', 'original_price',
       'discounted_price', 'Size1',
       'Size2', 'Size3', 'Size4',
       'Size5', 'Size6', 'Size7',
       'Size8', 'Size9', 'Size10',
       'Size11', 'opening_url', 'gender', 'colour1',
       'type', 'brand', 'selling_price', 'quality']

In [64]:
shoes = pd.concat([puma_Shoe1,Nike_Shoe,woodland_Shoe,adidas_Shoe],ignore_index=True)

In [65]:
shoes.to_csv('shoes.csv')

.

In [66]:
shoes = pd.read_csv('shoes.csv')
shoes

,Unnamed: 0,Name,original_price,discounted_price,Number_of_colour,Product_Code,Reviews,Rating,Size1,Size2,...,gender,brand,colour1,colour2,colour3,colour4,selling_price,quality,Size_Count,type
0,0,Star Vital Women's Training Shoes\nPUMA Black-...,5395.0,2656.0,2 COLORS,Style: 194331_19,Love the look the comfort the style the price ...,4.0,Size\n5.5,Size\n6,...,women,Puma,PUMA Black,PUMA Silver,NaN,NaN,2656.0,average,NaN,NaN
1,1,Better Foam Prowl Slip-On Wide Women's Trainin...,5395.0,2905.0,1 COLOR,Style: 376927_02,I purchase these abt 6 wks ago. The only compl...,3.0,Size\n5.5,Size\n6,...,women,Puma,Puma Black,Puma Black,NaN,NaN,2905.0,average,NaN,NaN
2,2,Suede Classic XXI Women's Sneakers\nIcy Blue-P...,6225.0,3237.0,7 COLORS,Style: 381410_85,These sneakers are cute and comfortable. They ...,4.0,Size\n6,Size\n6.5,...,women,Puma,Icy Blue,PUMA White,NaN,NaN,3237.0,good,NaN,NaN
3,3,Ella Lace Up Women's Shoes\nPuma White-Puma Si...,4980.0,2490.0,2 COLORS,Style: 193919_01,First time buying Puma shoes and really glad I...,4.0,Size\n5.5,Size\n6,...,women,Puma,Puma White,Puma Silver,NaN,NaN,2490.0,average,NaN,NaN
4,4,Star Vital Women's Training Shoes\nPuma Black-...,5395.0,2656.0,2 COLORS,Style: 194331_15,Love the look the comfort the style the price ...,4.0,Size\n5.5,Size\n6,...,women,Puma,Puma Black,Rose Gold,NaN,NaN,2656.0,average,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,1225,Ultrabounce Shoes,7999.0,NaN,13 colours,Upper contains a minimum of 50% recycled content,"Nice product\nDecember 12, 2023",4.6,NaN,NaN,...,men,adidas,Core Black,Gold Metallic,Cloud White,NaN,7999.0,good,NaN,Men Running
1226,1226,ADIZERO SL,11999.0,NaN,11 colours · win race,Upper contains a minimum of 50% recycled content,"Good daily trainer\nDecember 12, 2023",4.5,NaN,NaN,...,men,adidas,Lucid Cyan,Black Blue Met.S19,Wonder Silver,NaN,11999.0,great,NaN,Men Running
1227,1227,Racer TR23 Shoes,7999.0,NaN,6 colours · online exclusive,Colour: Carbon / Core Black / Royal Blue,"Light and comfortable !\nDecember 11, 2023",4.6,NaN,NaN,...,men,adidas,Carbon,Core Black,Royal Blue,NaN,7999.0,good,NaN,Men Running
1228,1228,Ultraboost Light Shoes,18999.0,NaN,15 colours · responsive run,Continental™ Better Rubber outsole,"Good product\nDecember 12, 2023",4.7,NaN,NaN,...,men,adidas,Dark Blue,Cream White,Core Black,NaN,18999.0,best,NaN,Running
1229,1229,VL Court 3.0 Shoes,7599.0,NaN,2 colours,Colour: Cloud White / Core Black / Grey One,_,_,NaN,NaN,...,men,adidas,Cloud White,Core Black,Grey One,NaN,7599.0,good,NaN,Men sportswear

In [67]:
shoes['gender'].value_counts()

men      725
women    505
Name: gender, dtype: int64

In [68]:
d=shoes['Size1'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size1'] = a

d=shoes['Size2'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size2'] = a

d=shoes['Size3'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size3'] = a

d=shoes['Size4'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size4'] = a

d=shoes['Size5'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size5'] = a

d=shoes['Size6'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size6'] = a

d=shoes['Size7'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size7'] = a

d=shoes['Size8'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size8'] = a

d=shoes['Size9'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size9'] = a

d=shoes['Size10'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size10'] = a

d=shoes['Size11'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size11'] = a

d=shoes['Size12'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size12'] = a

d=shoes['Size13'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size13'] = a

d=shoes['Size14'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size14'] = a

d=shoes['Size15'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size15'] = a

d=shoes['Size16'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size16'] = a

d=shoes['Size17'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size17'] = a

d=shoes['Size18'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size18'] = a

d=shoes['Size19'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size19'] = a

d=shoes['Size20'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size20'] = a

d=shoes['Size21'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size21'] = a

d=shoes['Size22'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size22'] = a

d=shoes['Size23'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size23'] = a

d=shoes['Size24'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size24'] = a

d=shoes['Size25'].str.replace(' ','')
a=d.str.extract('(\d+)')
shoes['Size25'] = a

In [69]:
na = shoes[['Size1',
       'Size2', 'Size3', 'Size4', 'Size5', 'Size6', 'Size7', 'Size8', 'Size9',
       'Size10', 'Size11', 'Size_Count', 'Size12',
       'Size13', 'Size14', 'Size15', 'Size16', 'Size17', 'Size18', 'Size19',
       'Size20', 'Size21', 'Size22', 'Size23', 'Size24', 'Size25']]

In [70]:
na = na.dropna(how='all')
na

,Size1,Size2,Size3,Size4,Size5,Size6,Size7,Size8,Size9,Size10,...,Size16,Size17,Size18,Size19,Size20,Size21,Size22,Size23,Size24,Size25
0,5,6,6,7,7,8,8,9,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,6,6,7,7,8,8,9,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6,6,7,7,8,8,9,9,10,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,6,6,7,7,8,8,9,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,6,6,7,7,8,8,9,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920,35,36,37,38,39,40,41,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
921,35,36,37,38,39,40,41,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
922,35,36,37,38,39,40,41,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
923,35,36,37,38,39,40,41,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
924,35,36,37,38,39,40,41,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
def join(columns):
    return','.join([str(x) for x in columns if not pd.isna(x)])
shoes['all_sizes'] = na.apply(join,axis=1)

In [72]:
shoes['size_count'] = (shoes['all_sizes'].str.count(','))+1

In [73]:
shoes['size_count']

0       12.0
1       12.0
2       11.0
3       12.0
4       12.0
        ...
1225     NaN
1226     NaN
1227     NaN
1228     NaN
1229     NaN
Name: size_count, Length: 1230, dtype: float64

In [74]:
shoes=shoes.drop('Unnamed: 0',axis=1)

In [75]:
shoes['discount'] =shoes['discounted_price'].apply(lambda x: 'yes' if x>0 else 'no')
shoes = shoes.drop(['original_price','discounted_price'],axis=1)

In [76]:
shoes=shoes.drop(['Size1', 'Size2', 'Size3', 'Size4', 'Size5', 'Size6',
       'Size7', 'Size8', 'Size9', 'Size10', 'Size11',
       'Size12', 'Size13', 'Size14', 'Size15', 'Size16', 'Size17', 'Size18',
       'Size19', 'Size20', 'Size21', 'Size22', 'Size23', 'Size24', 'Size25','opening_url'],axis=1)

In [77]:
a = shoes['Number_of_colour'].str.extract('(\d+)')
shoes['Number_of_colour'] = a

In [78]:
shoes['type'].value_counts()

sportswear             193
casual                 150
loafers                 50
originals               45
Men Running             43
Running                 40
Women Running           25
Men sportswear          24
Lifestyle               19
Men originals           17
Women sportswear        10
Football                 8
Men Lifestyle            7
Women Walking            5
Basketball               5
Women Lifestyle          5
Men Basketball           4
Women Basketball         4
Men Tennis               3
y_3                      3
Women Swim               2
Women Skateboarding      1
Swim                     1
Women Tennis             1
Women Training           1
Men Walking              1
Men Training             1
Men Outdoor              1
Skateboarding            1
Men Skateboarding        1
Women Outdoor            1
Men Track & Field        1
Women originals          1
Men Hiking               1
Name: type, dtype: int64

In [79]:
mapin = {'casual':1,'loafers':1,'originals':1,'Lifestyle':1,'Men originals':1,
'Women Lifestyle':1}

def types(type):
    if type in mapin.keys():
        return mapin[type]
    else:
        return 0
    
shoes['Types1'] = shoes['type'].apply(types)

In [80]:
mapin = {'sportswear':1,'Men Running':1,'Running':1,'Women Running':1,'Men sportswear':1,
'Women sportswear':1,'Football':1,'Basketball':1,'Women Basketball':1,'Men Training':1}

def types(type):
    if type in mapin.keys():
        return mapin[type]
    else:
        return 0
    
shoes['Types2'] = shoes['type'].apply(types)

In [81]:
shoes['Rating'] = shoes['Rating'].replace('_',0)
shoes['Rating'] = shoes['Rating'].astype(float)

In [82]:
shoes = shoes.drop('Size_Count',axis=1)

In [83]:
allcolors = shoes[['colour1','colour2','colour3','colour4']]

def join(columns):
    return','.join([str(x) for x in columns if not pd.isna(x)])
allcolors = allcolors.apply(join,axis=1)

In [84]:
allcolors

0                                PUMA Black,PUMA Silver
1                                 Puma Black,Puma Black
2                                   Icy Blue,PUMA White
3                                Puma White,Puma Silver
4                                  Puma Black,Rose Gold
                             ...
1225           Core Black , Gold Metallic , Cloud White
1226    Lucid Cyan , Black Blue Met.S19 , Wonder Silver
1227                   Carbon , Core Black , Royal Blue
1228               Dark Blue , Cream White , Core Black
1229                Cloud White , Core Black , Grey One
Length: 1230, dtype: object

In [85]:
shoes['colors_count'] = (allcolors.str.count(','))+1

In [86]:
shoes['colors_count']

0       2
1       2
2       2
3       2
4       2
       ..
1225    3
1226    3
1227    3
1228    3
1229    3
Name: colors_count, Length: 1230, dtype: int64

In [87]:
shoes

,Name,Number_of_colour,Product_Code,Reviews,Rating,gender,brand,colour1,colour2,colour3,colour4,selling_price,quality,type,all_sizes,size_count,discount,Types1,Types2,colors_count
0,Star Vital Women's Training Shoes\nPUMA Black-...,2,Style: 194331_19,Love the look the comfort the style the price ...,4.0,women,Puma,PUMA Black,PUMA Silver,NaN,NaN,2656.0,average,NaN,"5,6,6,7,7,8,8,9,9,10,10,11",12.0,yes,0,0,2
1,Better Foam Prowl Slip-On Wide Women's Trainin...,1,Style: 376927_02,I purchase these abt 6 wks ago. The only compl...,3.0,women,Puma,Puma Black,Puma Black,NaN,NaN,2905.0,average,NaN,"5,6,6,7,7,8,8,9,9,10,10,11",12.0,yes,0,0,2
2,Suede Classic XXI Women's Sneakers\nIcy Blue-P...,7,Style: 381410_85,These sneakers are cute and comfortable. They ...,4.0,women,Puma,Icy Blue,PUMA White,NaN,NaN,3237.0,good,NaN,"6,6,7,7,8,8,9,9,10,10,11",11.0,yes,0,0,2
3,Ella Lace Up Women's Shoes\nPuma White-Puma Si...,2,Style: 193919_01,First time buying Puma shoes and really glad I...,4.0,women,Puma,Puma White,Puma Silver,NaN,NaN,2490.0,average,NaN,"5,6,6,7,7,8,8,9,9,10,10,11",12.0,yes,0,0,2
4,Star Vital Women's Training Shoes\nPuma Black-...,2,Style: 194331_15,Love the look the comfort the style the price ...,4.0,women,Puma,Puma Black,Rose Gold,NaN,NaN,2656.0,average,NaN,"5,6,6,7,7,8,8,9,9,10,10,11",12.0,yes,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Ultrabounce Shoes,13,Upper contains a minimum of 50% recycled content,"Nice product\nDecember 12, 2023",4.6,men,adidas,Core Black,Gold Metallic,Cloud White,NaN,7999.0,good,Men Running,NaN,NaN,no,0,1,3
1226,ADIZERO SL,11,Upper contains a minimum of 50% recycled content,"Good daily trainer\nDecember 12, 2023",4.5,men,adidas,Lucid Cyan,Black Blue Met.S19,Wonder Silver,NaN,11999.0,great,Men Running,NaN,NaN,no,0,1,3
1227,Racer TR23 Shoes,6,Colour: Carbon / Core Black / Royal Blue,"Light and comfortable !\nDecember 11, 2023",4.6,men,adidas,Carbon,Core Black,Royal Blue,NaN,7999.0,good,Men Running,NaN,NaN,no,0,1,3
1228,Ultraboost Light Shoes,15,Continental™ Better Rubber outsole,"Good product\nDecember 12, 2023",4.7,men,adidas,Dark Blue,Cream White,Core Black,NaN,18999.0,best,Running,NaN,NaN,no,0,1,3
1229,VL Court 3.0 Shoes,2,Colour: Cloud White / Core Black / Grey One,_,0.0,men,adidas,Cloud White,Core Black,Grey One,NaN,7599.0,good,Men sportswear,NaN,NaN,no,0,1,3

In [5]:
shoesfinal.quality.value_counts()

good       507
great      304
best       210
average    209
Name: quality, dtype: int64

In [88]:
shoes.to_csv('shoesfinal.csv')

In [3]:
shoesfinal = pd.read_csv('shoesfinal.csv')

In [4]:
shoesfinal.isnull().sum()

Unnamed: 0             0
Name                   0
Number_of_colour     460
Product_Code         370
Reviews              370
Rating               382
gender                 0
brand                  0
colour1                5
colour2              482
colour3              669
colour4             1079
selling_price         17
quality                0
type                 555
all_sizes            352
size_count           352
discount               0
Types1                 0
Types2                 0
colors_count           0
dtype: int64

In [5]:
shoesfinal[['Number_of_colour','Product_Code','Rating','selling_price','all_sizes','size_count']] = shoesfinal[['Number_of_colour','Product_Code','Rating','selling_price','all_sizes','size_count']].fillna(-1)
shoesfinal[['Reviews','colour1','colour2','colour3','colour4','type']] = shoesfinal[['Reviews','colour1','colour2','colour3','colour4','type']].fillna('NA')

In [6]:
shoesfinal.isnull().sum()

Unnamed: 0          0
Name                0
Number_of_colour    0
Product_Code        0
Reviews             0
Rating              0
gender              0
brand               0
colour1             0
colour2             0
colour3             0
colour4             0
selling_price       0
quality             0
type                0
all_sizes           0
size_count          0
discount            0
Types1              0
Types2              0
colors_count        0
dtype: int64

In [8]:
qual = {'good':1,'great':2,'best':3,}

def types(type):
    if type in qual.keys():
        return qual[type]
    else:
        return 0
    
shoesfinal['quality'] = shoesfinal['quality'].apply(types)

In [11]:
shoesfinal['id'] = range(1,1231)

cc = shoesfinal[['colour1','colour2','colour3','colour4']]
def join(columns):
    return','.join([str(x) for x in columns if not pd.isna(x)])
shoesfinal['all_colors'] = cc.apply(join,axis=1)

In [12]:
shoesfinal

,Unnamed: 0,Name,Number_of_colour,Product_Code,Reviews,Rating,gender,brand,colour1,colour2,...,selling_price,quality,type,all_sizes,size_count,discount,Types1,Types2,colors_count,id
0,0,Star Vital Women's Training Shoes\nPUMA Black-...,2.0,Style: 194331_19,Love the look the comfort the style the price ...,4.0,women,Puma,PUMA Black,PUMA Silver,...,2656.0,0,NA,"5,6,6,7,7,8,8,9,9,10,10,11",12.0,yes,0,0,2,1
1,1,Better Foam Prowl Slip-On Wide Women's Trainin...,1.0,Style: 376927_02,I purchase these abt 6 wks ago. The only compl...,3.0,women,Puma,Puma Black,Puma Black,...,2905.0,0,NA,"5,6,6,7,7,8,8,9,9,10,10,11",12.0,yes,0,0,2,2
2,2,Suede Classic XXI Women's Sneakers\nIcy Blue-P...,7.0,Style: 381410_85,These sneakers are cute and comfortable. They ...,4.0,women,Puma,Icy Blue,PUMA White,...,3237.0,1,NA,"6,6,7,7,8,8,9,9,10,10,11",11.0,yes,0,0,2,3
3,3,Ella Lace Up Women's Shoes\nPuma White-Puma Si...,2.0,Style: 193919_01,First time buying Puma shoes and really glad I...,4.0,women,Puma,Puma White,Puma Silver,...,2490.0,0,NA,"5,6,6,7,7,8,8,9,9,10,10,11",12.0,yes,0,0,2,4
4,4,Star Vital Women's Training Shoes\nPuma Black-...,2.0,Style: 194331_15,Love the look the comfort the style the price ...,4.0,women,Puma,Puma Black,Rose Gold,...,2656.0,0,NA,"5,6,6,7,7,8,8,9,9,10,10,11",12.0,yes,0,0,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,1225,Ultrabounce Shoes,13.0,Upper contains a minimum of 50% recycled content,"Nice product\nDecember 12, 2023",4.6,men,adidas,Core Black,Gold Metallic,...,7999.0,1,Men Running,-1,-1.0,no,0,1,3,1226
1226,1226,ADIZERO SL,11.0,Upper contains a minimum of 50% recycled content,"Good daily trainer\nDecember 12, 2023",4.5,men,adidas,Lucid Cyan,Black Blue Met.S19,...,11999.0,2,Men Running,-1,-1.0,no,0,1,3,1227
1227,1227,Racer TR23 Shoes,6.0,Colour: Carbon / Core Black / Royal Blue,"Light and comfortable !\nDecember 11, 2023",4.6,men,adidas,Carbon,Core Black,...,7999.0,1,Men Running,-1,-1.0,no,0,1,3,1228
1228,1228,Ultraboost Light Shoes,15.0,Continental™ Better Rubber outsole,"Good product\nDecember 12, 2023",4.7,men,adidas,Dark Blue,Cream White,...,18999.0,3,Running,-1,-1.0,no,0,1,3,1229
1229,1229,VL Court 3.0 Shoes,2.0,Colour: Cloud White / Core Black / Grey One,_,0.0,men,adidas,Cloud White,Core Black,...,7599.0,1,Men sportswear,-1,-1.0,no,0,1,3,1230

In [13]:
shoesfinal.shape

(1230, 22)

.

.

In [14]:
Table1 = shoesfinal[['id','Name','gender','Number_of_colour','selling_price','colors_count','colour1','colour2','colour3','colour4']]
Table1.to_csv('Table1.csv')
Table1.head()

,id,Name,gender,Number_of_colour,selling_price,colors_count,colour1,colour2,colour3,colour4
0,1,Star Vital Women's Training Shoes\nPUMA Black-...,women,2.0,2656.0,2,PUMA Black,PUMA Silver,NA,NA
1,2,Better Foam Prowl Slip-On Wide Women's Trainin...,women,1.0,2905.0,2,Puma Black,Puma Black,NA,NA
2,3,Suede Classic XXI Women's Sneakers\nIcy Blue-P...,women,7.0,3237.0,2,Icy Blue,PUMA White,NA,NA
3,4,Ella Lace Up Women's Shoes\nPuma White-Puma Si...,women,2.0,2490.0,2,Puma White,Puma Silver,NA,NA
4,5,Star Vital Women's Training Shoes\nPuma Black-...,women,2.0,2656.0,2,Puma Black,Rose Gold,NA,NA

In [18]:
# we have to includer number of colors column but in one of the sqlquery we have to use color name , thats why i added color column
# 'Number_of_colour' is mentioned in the main page and i obtained count of colors from counting the number of color mentioned inside the opening_url

In [20]:
Table2 = shoesfinal[['id','size_count','colour1','colour2','colour3','colour4','Product_Code','colors_count','Number_of_colour']]
Table2.to_csv('Table2.csv')
Table2.head()

,id,size_count,colour1,colour2,colour3,colour4,Product_Code,colors_count,Number_of_colour
0,1,12.0,PUMA Black,PUMA Silver,NA,NA,Style: 194331_19,2,2.0
1,2,12.0,Puma Black,Puma Black,NA,NA,Style: 376927_02,2,1.0
2,3,11.0,Icy Blue,PUMA White,NA,NA,Style: 381410_85,2,7.0
3,4,12.0,Puma White,Puma Silver,NA,NA,Style: 193919_01,2,2.0
4,5,12.0,Puma Black,Rose Gold,NA,NA,Style: 194331_15,2,2.0

In [19]:
# Number_of_colour or colors_count is required for sql table_2 question number 3

In [16]:
Table3 = shoesfinal[['id','Reviews','all_sizes','quality','Rating']]
Table3.to_csv('Table3.csv')
Table3.head()

,id,Reviews,all_sizes,quality,Rating
0,1,Love the look the comfort the style the price ...,"5,6,6,7,7,8,8,9,9,10,10,11",0,4.0
1,2,I purchase these abt 6 wks ago. The only compl...,"5,6,6,7,7,8,8,9,9,10,10,11",0,3.0
2,3,These sneakers are cute and comfortable. They ...,"6,6,7,7,8,8,9,9,10,10,11",1,4.0
3,4,First time buying Puma shoes and really glad I...,"5,6,6,7,7,8,8,9,9,10,10,11",0,4.0
4,5,Love the look the comfort the style the price ...,"5,6,6,7,7,8,8,9,9,10,10,11",0,4.0

In [17]:
# creating a common column 'id' in all these because some rows are removed or not added when i import the csv file in MYsql and it will create problems when i use join query so i created a new common column